/**
 *
 *  AuditLogs.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "AuditLogs.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::fulla_db;

const std::string AuditLogs::Cols::_id = "\"id\"";
const std::string AuditLogs::Cols::_timestamp = "\"timestamp\"";
const std::string AuditLogs::Cols::_actor_type = "\"actor_type\"";
const std::string AuditLogs::Cols::_actor_id = "\"actor_id\"";
const std::string AuditLogs::Cols::_action = "\"action\"";
const std::string AuditLogs::Cols::_target_type = "\"target_type\"";
const std::string AuditLogs::Cols::_target_id = "\"target_id\"";
const std::string AuditLogs::Cols::_outcome = "\"outcome\"";
const std::string AuditLogs::Cols::_ip = "\"ip\"";
const std::string AuditLogs::Cols::_user_agent = "\"user_agent\"";
const std::string AuditLogs::Cols::_request_id = "\"request_id\"";
const std::string AuditLogs::Cols::_details = "\"details\"";
const std::string AuditLogs::Cols::_org_id = "\"org_id\"";
const std::vector<std::string> AuditLogs::primaryKeyName = {"id","timestamp"};
const bool AuditLogs::hasPrimaryKey = true;
const std::string AuditLogs::tableName = "\"audit_logs\"";

const std::vector<typename AuditLogs::MetaData> AuditLogs::metaData_={
{"id","int64_t","bigint",8,1,1,1},
{"timestamp","::trantor::Date","timestamp with time zone",0,0,1,1},
{"actor_type","std::string","character varying",20,0,0,1},
{"actor_id","std::string","character varying",128,0,0,0},
{"action","std::string","character varying",50,0,0,1},
{"target_type","std::string","character varying",30,0,0,0},
{"target_id","std::string","character varying",128,0,0,0},
{"outcome","std::string","character varying",10,0,0,1},
{"ip","std::string","character varying",45,0,0,0},
{"user_agent","std::string","text",0,0,0,0},
{"request_id","std::string","character varying",64,0,0,0},
{"details","std::string","jsonb",0,0,0,0},
{"org_id","int32_t","integer",4,0,0,0}
};
const std::string &AuditLogs::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
AuditLogs::AuditLogs(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int64_t>(r["id"].as<int64_t>());
        }
        if(!r["timestamp"].isNull())
        {
            auto timeStr = r["timestamp"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                timestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["actor_type"].isNull())
        {
            actorType_=std::make_shared<std::string>(r["actor_type"].as<std::string>());
        }
        if(!r["actor_id"].isNull())
        {
            actorId_=std::make_shared<std::string>(r["actor_id"].as<std::string>());
        }
        if(!r["action"].isNull())
        {
            action_=std::make_shared<std::string>(r["action"].as<std::string>());
        }
        if(!r["target_type"].isNull())
        {
            targetType_=std::make_shared<std::string>(r["target_type"].as<std::string>());
        }
        if(!r["target_id"].isNull())
        {
            targetId_=std::make_shared<std::string>(r["target_id"].as<std::string>());
        }
        if(!r["outcome"].isNull())
        {
            outcome_=std::make_shared<std::string>(r["outcome"].as<std::string>());
        }
        if(!r["ip"].isNull())
        {
            ip_=std::make_shared<std::string>(r["ip"].as<std::string>());
        }
        if(!r["user_agent"].isNull())
        {
            userAgent_=std::make_shared<std::string>(r["user_agent"].as<std::string>());
        }
        if(!r["request_id"].isNull())
        {
            requestId_=std::make_shared<std::string>(r["request_id"].as<std::string>());
        }
        if(!r["details"].isNull())
        {
            details_=std::make_shared<std::string>(r["details"].as<std::string>());
        }
        if(!r["org_id"].isNull())
        {
            orgId_=std::make_shared<int32_t>(r["org_id"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 13 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                timestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            actorType_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            actorId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            action_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            targetType_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            targetId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            outcome_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            ip_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            userAgent_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            requestId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 11;
        if(!r[index].isNull())
        {
            details_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 12;
        if(!r[index].isNull())
        {
            orgId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

AuditLogs::AuditLogs(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 13)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[1]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                timestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            actorType_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            actorId_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            action_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            targetType_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            targetId_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            outcome_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            ip_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            userAgent_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            requestId_=std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            details_=std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            orgId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[12]].asInt64());
        }
    }
}

AuditLogs::AuditLogs(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("timestamp"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["timestamp"].isNull())
        {
            auto timeStr = pJson["timestamp"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                timestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("actor_type"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["actor_type"].isNull())
        {
            actorType_=std::make_shared<std::string>(pJson["actor_type"].asString());
        }
    }
    if(pJson.isMember("actor_id"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["actor_id"].isNull())
        {
            actorId_=std::make_shared<std::string>(pJson["actor_id"].asString());
        }
    }
    if(pJson.isMember("action"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["action"].isNull())
        {
            action_=std::make_shared<std::string>(pJson["action"].asString());
        }
    }
    if(pJson.isMember("target_type"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["target_type"].isNull())
        {
            targetType_=std::make_shared<std::string>(pJson["target_type"].asString());
        }
    }
    if(pJson.isMember("target_id"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["target_id"].isNull())
        {
            targetId_=std::make_shared<std::string>(pJson["target_id"].asString());
        }
    }
    if(pJson.isMember("outcome"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["outcome"].isNull())
        {
            outcome_=std::make_shared<std::string>(pJson["outcome"].asString());
        }
    }
    if(pJson.isMember("ip"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["ip"].isNull())
        {
            ip_=std::make_shared<std::string>(pJson["ip"].asString());
        }
    }
    if(pJson.isMember("user_agent"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["user_agent"].isNull())
        {
            userAgent_=std::make_shared<std::string>(pJson["user_agent"].asString());
        }
    }
    if(pJson.isMember("request_id"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["request_id"].isNull())
        {
            requestId_=std::make_shared<std::string>(pJson["request_id"].asString());
        }
    }
    if(pJson.isMember("details"))
    {
        dirtyFlag_[11]=true;
        if(!pJson["details"].isNull())
        {
            details_=std::make_shared<std::string>(pJson["details"].asString());
        }
    }
    if(pJson.isMember("org_id"))
    {
        dirtyFlag_[12]=true;
        if(!pJson["org_id"].isNull())
        {
            orgId_=std::make_shared<int32_t>((int32_t)pJson["org_id"].asInt64());
        }
    }
}

void AuditLogs::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 13)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[1]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                timestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            actorType_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            actorId_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            action_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            targetType_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            targetId_=std::make_shared<std::string>(pJson[pMasqueradingVector[6]].asString());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            outcome_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            ip_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            userAgent_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            requestId_=std::make_shared<std::string>(pJson[pMasqueradingVector[10]].asString());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            details_=std::make_shared<std::string>(pJson[pMasqueradingVector[11]].asString());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            orgId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[12]].asInt64());
        }
    }
}

void AuditLogs::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int64_t>((int64_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("timestamp"))
    {
        if(!pJson["timestamp"].isNull())
        {
            auto timeStr = pJson["timestamp"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                timestamp_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("actor_type"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["actor_type"].isNull())
        {
            actorType_=std::make_shared<std::string>(pJson["actor_type"].asString());
        }
    }
    if(pJson.isMember("actor_id"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["actor_id"].isNull())
        {
            actorId_=std::make_shared<std::string>(pJson["actor_id"].asString());
        }
    }
    if(pJson.isMember("action"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["action"].isNull())
        {
            action_=std::make_shared<std::string>(pJson["action"].asString());
        }
    }
    if(pJson.isMember("target_type"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["target_type"].isNull())
        {
            targetType_=std::make_shared<std::string>(pJson["target_type"].asString());
        }
    }
    if(pJson.isMember("target_id"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["target_id"].isNull())
        {
            targetId_=std::make_shared<std::string>(pJson["target_id"].asString());
        }
    }
    if(pJson.isMember("outcome"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["outcome"].isNull())
        {
            outcome_=std::make_shared<std::string>(pJson["outcome"].asString());
        }
    }
    if(pJson.isMember("ip"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["ip"].isNull())
        {
            ip_=std::make_shared<std::string>(pJson["ip"].asString());
        }
    }
    if(pJson.isMember("user_agent"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["user_agent"].isNull())
        {
            userAgent_=std::make_shared<std::string>(pJson["user_agent"].asString());
        }
    }
    if(pJson.isMember("request_id"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["request_id"].isNull())
        {
            requestId_=std::make_shared<std::string>(pJson["request_id"].asString());
        }
    }
    if(pJson.isMember("details"))
    {
        dirtyFlag_[11] = true;
        if(!pJson["details"].isNull())
        {
            details_=std::make_shared<std::string>(pJson["details"].asString());
        }
    }
    if(pJson.isMember("org_id"))
    {
        dirtyFlag_[12] = true;
        if(!pJson["org_id"].isNull())
        {
            orgId_=std::make_shared<int32_t>((int32_t)pJson["org_id"].asInt64());
        }
    }
}

const int64_t &AuditLogs::getValueOfId() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &AuditLogs::getId() const noexcept
{
    return id_;
}
void AuditLogs::setId(const int64_t &pId) noexcept
{
    id_ = std::make_shared<int64_t>(pId);
    dirtyFlag_[0] = true;
}

const ::trantor::Date &AuditLogs::getValueOfTimestamp() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(timestamp_)
        return *timestamp_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &AuditLogs::getTimestamp() const noexcept
{
    return timestamp_;
}
void AuditLogs::setTimestamp(const ::trantor::Date &pTimestamp) noexcept
{
    timestamp_ = std::make_shared<::trantor::Date>(pTimestamp);
    dirtyFlag_[1] = true;
}

const std::string &AuditLogs::getValueOfActorType() const noexcept
{
    static const std::string defaultValue = std::string();
    if(actorType_)
        return *actorType_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLogs::getActorType() const noexcept
{
    return actorType_;
}
void AuditLogs::setActorType(const std::string &pActorType) noexcept
{
    actorType_ = std::make_shared<std::string>(pActorType);
    dirtyFlag_[2] = true;
}
void AuditLogs::setActorType(std::string &&pActorType) noexcept
{
    actorType_ = std::make_shared<std::string>(std::move(pActorType));
    dirtyFlag_[2] = true;
}

const std::string &AuditLogs::getValueOfActorId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(actorId_)
        return *actorId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLogs::getActorId() const noexcept
{
    return actorId_;
}
void AuditLogs::setActorId(const std::string &pActorId) noexcept
{
    actorId_ = std::make_shared<std::string>(pActorId);
    dirtyFlag_[3] = true;
}
void AuditLogs::setActorId(std::string &&pActorId) noexcept
{
    actorId_ = std::make_shared<std::string>(std::move(pActorId));
    dirtyFlag_[3] = true;
}
void AuditLogs::setActorIdToNull() noexcept
{
    actorId_.reset();
    dirtyFlag_[3] = true;
}

const std::string &AuditLogs::getValueOfAction() const noexcept
{
    static const std::string defaultValue = std::string();
    if(action_)
        return *action_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLogs::getAction() const noexcept
{
    return action_;
}
void AuditLogs::setAction(const std::string &pAction) noexcept
{
    action_ = std::make_shared<std::string>(pAction);
    dirtyFlag_[4] = true;
}
void AuditLogs::setAction(std::string &&pAction) noexcept
{
    action_ = std::make_shared<std::string>(std::move(pAction));
    dirtyFlag_[4] = true;
}

const std::string &AuditLogs::getValueOfTargetType() const noexcept
{
    static const std::string defaultValue = std::string();
    if(targetType_)
        return *targetType_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLogs::getTargetType() const noexcept
{
    return targetType_;
}
void AuditLogs::setTargetType(const std::string &pTargetType) noexcept
{
    targetType_ = std::make_shared<std::string>(pTargetType);
    dirtyFlag_[5] = true;
}
void AuditLogs::setTargetType(std::string &&pTargetType) noexcept
{
    targetType_ = std::make_shared<std::string>(std::move(pTargetType));
    dirtyFlag_[5] = true;
}
void AuditLogs::setTargetTypeToNull() noexcept
{
    targetType_.reset();
    dirtyFlag_[5] = true;
}

const std::string &AuditLogs::getValueOfTargetId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(targetId_)
        return *targetId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLogs::getTargetId() const noexcept
{
    return targetId_;
}
void AuditLogs::setTargetId(const std::string &pTargetId) noexcept
{
    targetId_ = std::make_shared<std::string>(pTargetId);
    dirtyFlag_[6] = true;
}
void AuditLogs::setTargetId(std::string &&pTargetId) noexcept
{
    targetId_ = std::make_shared<std::string>(std::move(pTargetId));
    dirtyFlag_[6] = true;
}
void AuditLogs::setTargetIdToNull() noexcept
{
    targetId_.reset();
    dirtyFlag_[6] = true;
}

const std::string &AuditLogs::getValueOfOutcome() const noexcept
{
    static const std::string defaultValue = std::string();
    if(outcome_)
        return *outcome_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLogs::getOutcome() const noexcept
{
    return outcome_;
}
void AuditLogs::setOutcome(const std::string &pOutcome) noexcept
{
    outcome_ = std::make_shared<std::string>(pOutcome);
    dirtyFlag_[7] = true;
}
void AuditLogs::setOutcome(std::string &&pOutcome) noexcept
{
    outcome_ = std::make_shared<std::string>(std::move(pOutcome));
    dirtyFlag_[7] = true;
}

const std::string &AuditLogs::getValueOfIp() const noexcept
{
    static const std::string defaultValue = std::string();
    if(ip_)
        return *ip_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLogs::getIp() const noexcept
{
    return ip_;
}
void AuditLogs::setIp(const std::string &pIp) noexcept
{
    ip_ = std::make_shared<std::string>(pIp);
    dirtyFlag_[8] = true;
}
void AuditLogs::setIp(std::string &&pIp) noexcept
{
    ip_ = std::make_shared<std::string>(std::move(pIp));
    dirtyFlag_[8] = true;
}
void AuditLogs::setIpToNull() noexcept
{
    ip_.reset();
    dirtyFlag_[8] = true;
}

const std::string &AuditLogs::getValueOfUserAgent() const noexcept
{
    static const std::string defaultValue = std::string();
    if(userAgent_)
        return *userAgent_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLogs::getUserAgent() const noexcept
{
    return userAgent_;
}
void AuditLogs::setUserAgent(const std::string &pUserAgent) noexcept
{
    userAgent_ = std::make_shared<std::string>(pUserAgent);
    dirtyFlag_[9] = true;
}
void AuditLogs::setUserAgent(std::string &&pUserAgent) noexcept
{
    userAgent_ = std::make_shared<std::string>(std::move(pUserAgent));
    dirtyFlag_[9] = true;
}
void AuditLogs::setUserAgentToNull() noexcept
{
    userAgent_.reset();
    dirtyFlag_[9] = true;
}

const std::string &AuditLogs::getValueOfRequestId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(requestId_)
        return *requestId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLogs::getRequestId() const noexcept
{
    return requestId_;
}
void AuditLogs::setRequestId(const std::string &pRequestId) noexcept
{
    requestId_ = std::make_shared<std::string>(pRequestId);
    dirtyFlag_[10] = true;
}
void AuditLogs::setRequestId(std::string &&pRequestId) noexcept
{
    requestId_ = std::make_shared<std::string>(std::move(pRequestId));
    dirtyFlag_[10] = true;
}
void AuditLogs::setRequestIdToNull() noexcept
{
    requestId_.reset();
    dirtyFlag_[10] = true;
}

const std::string &AuditLogs::getValueOfDetails() const noexcept
{
    static const std::string defaultValue = std::string();
    if(details_)
        return *details_;
    return defaultValue;
}
const std::shared_ptr<std::string> &AuditLogs::getDetails() const noexcept
{
    return details_;
}
void AuditLogs::setDetails(const std::string &pDetails) noexcept
{
    details_ = std::make_shared<std::string>(pDetails);
    dirtyFlag_[11] = true;
}
void AuditLogs::setDetails(std::string &&pDetails) noexcept
{
    details_ = std::make_shared<std::string>(std::move(pDetails));
    dirtyFlag_[11] = true;
}
void AuditLogs::setDetailsToNull() noexcept
{
    details_.reset();
    dirtyFlag_[11] = true;
}

const int32_t &AuditLogs::getValueOfOrgId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(orgId_)
        return *orgId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &AuditLogs::getOrgId() const noexcept
{
    return orgId_;
}
void AuditLogs::setOrgId(const int32_t &pOrgId) noexcept
{
    orgId_ = std::make_shared<int32_t>(pOrgId);
    dirtyFlag_[12] = true;
}
void AuditLogs::setOrgIdToNull() noexcept
{
    orgId_.reset();
    dirtyFlag_[12] = true;
}

void AuditLogs::updateId(const uint64_t id)
{
}
typename AuditLogs::PrimaryKeyType AuditLogs::getPrimaryKey() const
{
    return std::make_tuple(*id_,*timestamp_);
}

const std::vector<std::string> &AuditLogs::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "timestamp",
        "actor_type",
        "actor_id",
        "action",
        "target_type",
        "target_id",
        "outcome",
        "ip",
        "user_agent",
        "request_id",
        "details",
        "org_id"
    };
    return inCols;
}

void AuditLogs::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getTimestamp())
        {
            binder << getValueOfTimestamp();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getActorType())
        {
            binder << getValueOfActorType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getActorId())
        {
            binder << getValueOfActorId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getAction())
        {
            binder << getValueOfAction();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getTargetType())
        {
            binder << getValueOfTargetType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getTargetId())
        {
            binder << getValueOfTargetId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getOutcome())
        {
            binder << getValueOfOutcome();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getIp())
        {
            binder << getValueOfIp();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getUserAgent())
        {
            binder << getValueOfUserAgent();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getRequestId())
        {
            binder << getValueOfRequestId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getDetails())
        {
            binder << getValueOfDetails();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getOrgId())
        {
            binder << getValueOfOrgId();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> AuditLogs::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    if(dirtyFlag_[11])
    {
        ret.push_back(getColumnName(11));
    }
    if(dirtyFlag_[12])
    {
        ret.push_back(getColumnName(12));
    }
    return ret;
}

void AuditLogs::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getTimestamp())
        {
            binder << getValueOfTimestamp();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getActorType())
        {
            binder << getValueOfActorType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getActorId())
        {
            binder << getValueOfActorId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getAction())
        {
            binder << getValueOfAction();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getTargetType())
        {
            binder << getValueOfTargetType();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getTargetId())
        {
            binder << getValueOfTargetId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getOutcome())
        {
            binder << getValueOfOutcome();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getIp())
        {
            binder << getValueOfIp();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getUserAgent())
        {
            binder << getValueOfUserAgent();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getRequestId())
        {
            binder << getValueOfRequestId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getDetails())
        {
            binder << getValueOfDetails();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getOrgId())
        {
            binder << getValueOfOrgId();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value AuditLogs::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getTimestamp())
    {
        ret["timestamp"]=getTimestamp()->toDbStringLocal();
    }
    else
    {
        ret["timestamp"]=Json::Value();
    }
    if(getActorType())
    {
        ret["actor_type"]=getValueOfActorType();
    }
    else
    {
        ret["actor_type"]=Json::Value();
    }
    if(getActorId())
    {
        ret["actor_id"]=getValueOfActorId();
    }
    else
    {
        ret["actor_id"]=Json::Value();
    }
    if(getAction())
    {
        ret["action"]=getValueOfAction();
    }
    else
    {
        ret["action"]=Json::Value();
    }
    if(getTargetType())
    {
        ret["target_type"]=getValueOfTargetType();
    }
    else
    {
        ret["target_type"]=Json::Value();
    }
    if(getTargetId())
    {
        ret["target_id"]=getValueOfTargetId();
    }
    else
    {
        ret["target_id"]=Json::Value();
    }
    if(getOutcome())
    {
        ret["outcome"]=getValueOfOutcome();
    }
    else
    {
        ret["outcome"]=Json::Value();
    }
    if(getIp())
    {
        ret["ip"]=getValueOfIp();
    }
    else
    {
        ret["ip"]=Json::Value();
    }
    if(getUserAgent())
    {
        ret["user_agent"]=getValueOfUserAgent();
    }
    else
    {
        ret["user_agent"]=Json::Value();
    }
    if(getRequestId())
    {
        ret["request_id"]=getValueOfRequestId();
    }
    else
    {
        ret["request_id"]=Json::Value();
    }
    if(getDetails())
    {
        ret["details"]=getValueOfDetails();
    }
    else
    {
        ret["details"]=Json::Value();
    }
    if(getOrgId())
    {
        ret["org_id"]=getValueOfOrgId();
    }
    else
    {
        ret["org_id"]=Json::Value();
    }
    return ret;
}

std::string AuditLogs::toString() const
{
    return toJson().toStyledString();
}

Json::Value AuditLogs::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 13)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=(Json::Int64)getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getTimestamp())
            {
                ret[pMasqueradingVector[1]]=getTimestamp()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getActorType())
            {
                ret[pMasqueradingVector[2]]=getValueOfActorType();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getActorId())
            {
                ret[pMasqueradingVector[3]]=getValueOfActorId();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getAction())
            {
                ret[pMasqueradingVector[4]]=getValueOfAction();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getTargetType())
            {
                ret[pMasqueradingVector[5]]=getValueOfTargetType();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getTargetId())
            {
                ret[pMasqueradingVector[6]]=getValueOfTargetId();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getOutcome())
            {
                ret[pMasqueradingVector[7]]=getValueOfOutcome();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getIp())
            {
                ret[pMasqueradingVector[8]]=getValueOfIp();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getUserAgent())
            {
                ret[pMasqueradingVector[9]]=getValueOfUserAgent();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getRequestId())
            {
                ret[pMasqueradingVector[10]]=getValueOfRequestId();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[11].empty())
        {
            if(getDetails())
            {
                ret[pMasqueradingVector[11]]=getValueOfDetails();
            }
            else
            {
                ret[pMasqueradingVector[11]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[12].empty())
        {
            if(getOrgId())
            {
                ret[pMasqueradingVector[12]]=getValueOfOrgId();
            }
            else
            {
                ret[pMasqueradingVector[12]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=(Json::Int64)getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getTimestamp())
    {
        ret["timestamp"]=getTimestamp()->toDbStringLocal();
    }
    else
    {
        ret["timestamp"]=Json::Value();
    }
    if(getActorType())
    {
        ret["actor_type"]=getValueOfActorType();
    }
    else
    {
        ret["actor_type"]=Json::Value();
    }
    if(getActorId())
    {
        ret["actor_id"]=getValueOfActorId();
    }
    else
    {
        ret["actor_id"]=Json::Value();
    }
    if(getAction())
    {
        ret["action"]=getValueOfAction();
    }
    else
    {
        ret["action"]=Json::Value();
    }
    if(getTargetType())
    {
        ret["target_type"]=getValueOfTargetType();
    }
    else
    {
        ret["target_type"]=Json::Value();
    }
    if(getTargetId())
    {
        ret["target_id"]=getValueOfTargetId();
    }
    else
    {
        ret["target_id"]=Json::Value();
    }
    if(getOutcome())
    {
        ret["outcome"]=getValueOfOutcome();
    }
    else
    {
        ret["outcome"]=Json::Value();
    }
    if(getIp())
    {
        ret["ip"]=getValueOfIp();
    }
    else
    {
        ret["ip"]=Json::Value();
    }
    if(getUserAgent())
    {
        ret["user_agent"]=getValueOfUserAgent();
    }
    else
    {
        ret["user_agent"]=Json::Value();
    }
    if(getRequestId())
    {
        ret["request_id"]=getValueOfRequestId();
    }
    else
    {
        ret["request_id"]=Json::Value();
    }
    if(getDetails())
    {
        ret["details"]=getValueOfDetails();
    }
    else
    {
        ret["details"]=Json::Value();
    }
    if(getOrgId())
    {
        ret["org_id"]=getValueOfOrgId();
    }
    else
    {
        ret["org_id"]=Json::Value();
    }
    return ret;
}

bool AuditLogs::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("timestamp"))
    {
        if(!validJsonOfField(1, "timestamp", pJson["timestamp"], err, true))
            return false;
    }
    if(pJson.isMember("actor_type"))
    {
        if(!validJsonOfField(2, "actor_type", pJson["actor_type"], err, true))
            return false;
    }
    else
    {
        err="The actor_type column cannot be null";
        return false;
    }
    if(pJson.isMember("actor_id"))
    {
        if(!validJsonOfField(3, "actor_id", pJson["actor_id"], err, true))
            return false;
    }
    if(pJson.isMember("action"))
    {
        if(!validJsonOfField(4, "action", pJson["action"], err, true))
            return false;
    }
    else
    {
        err="The action column cannot be null";
        return false;
    }
    if(pJson.isMember("target_type"))
    {
        if(!validJsonOfField(5, "target_type", pJson["target_type"], err, true))
            return false;
    }
    if(pJson.isMember("target_id"))
    {
        if(!validJsonOfField(6, "target_id", pJson["target_id"], err, true))
            return false;
    }
    if(pJson.isMember("outcome"))
    {
        if(!validJsonOfField(7, "outcome", pJson["outcome"], err, true))
            return false;
    }
    else
    {
        err="The outcome column cannot be null";
        return false;
    }
    if(pJson.isMember("ip"))
    {
        if(!validJsonOfField(8, "ip", pJson["ip"], err, true))
            return false;
    }
    if(pJson.isMember("user_agent"))
    {
        if(!validJsonOfField(9, "user_agent", pJson["user_agent"], err, true))
            return false;
    }
    if(pJson.isMember("request_id"))
    {
        if(!validJsonOfField(10, "request_id", pJson["request_id"], err, true))
            return false;
    }
    if(pJson.isMember("details"))
    {
        if(!validJsonOfField(11, "details", pJson["details"], err, true))
            return false;
    }
    if(pJson.isMember("org_id"))
    {
        if(!validJsonOfField(12, "org_id", pJson["org_id"], err, true))
            return false;
    }
    return true;
}
bool AuditLogs::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                   const std::vector<std::string> &pMasqueradingVector,
                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 13)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[7] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[11].empty())
      {
          if(pJson.isMember(pMasqueradingVector[11]))
          {
              if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[12].empty())
      {
          if(pJson.isMember(pMasqueradingVector[12]))
          {
              if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool AuditLogs::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("timestamp"))
    {
        if(!validJsonOfField(1, "timestamp", pJson["timestamp"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("actor_type"))
    {
        if(!validJsonOfField(2, "actor_type", pJson["actor_type"], err, false))
            return false;
    }
    if(pJson.isMember("actor_id"))
    {
        if(!validJsonOfField(3, "actor_id", pJson["actor_id"], err, false))
            return false;
    }
    if(pJson.isMember("action"))
    {
        if(!validJsonOfField(4, "action", pJson["action"], err, false))
            return false;
    }
    if(pJson.isMember("target_type"))
    {
        if(!validJsonOfField(5, "target_type", pJson["target_type"], err, false))
            return false;
    }
    if(pJson.isMember("target_id"))
    {
        if(!validJsonOfField(6, "target_id", pJson["target_id"], err, false))
            return false;
    }
    if(pJson.isMember("outcome"))
    {
        if(!validJsonOfField(7, "outcome", pJson["outcome"], err, false))
            return false;
    }
    if(pJson.isMember("ip"))
    {
        if(!validJsonOfField(8, "ip", pJson["ip"], err, false))
            return false;
    }
    if(pJson.isMember("user_agent"))
    {
        if(!validJsonOfField(9, "user_agent", pJson["user_agent"], err, false))
            return false;
    }
    if(pJson.isMember("request_id"))
    {
        if(!validJsonOfField(10, "request_id", pJson["request_id"], err, false))
            return false;
    }
    if(pJson.isMember("details"))
    {
        if(!validJsonOfField(11, "details", pJson["details"], err, false))
            return false;
    }
    if(pJson.isMember("org_id"))
    {
        if(!validJsonOfField(12, "org_id", pJson["org_id"], err, false))
            return false;
    }
    return true;
}
bool AuditLogs::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                 const std::vector<std::string> &pMasqueradingVector,
                                                 std::string &err)
{
    if(pMasqueradingVector.size() != 13)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
      if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
      {
          if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
              return false;
      }
      if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
      {
          if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool AuditLogs::validJsonOfField(size_t index,
                                 const std::string &fieldName,
                                 const Json::Value &pJson,
                                 std::string &err,
                                 bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 20)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 20)";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 128)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 128)";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 30)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 30)";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 128)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 128)";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 10)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 10)";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 45)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 45)";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 64)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 64)";
                return false;
            }
            break;
        case 11:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 12:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
