/**
 *
 *  Oauth2RefreshTokens.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Oauth2RefreshTokens.h"
#include "Oauth2Clients.h"
#include "Organizations.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::fulla_db;

const std::string Oauth2RefreshTokens::Cols::_token = "\"token\"";
const std::string Oauth2RefreshTokens::Cols::_access_token = "\"access_token\"";
const std::string Oauth2RefreshTokens::Cols::_client_id = "\"client_id\"";
const std::string Oauth2RefreshTokens::Cols::_user_id = "\"user_id\"";
const std::string Oauth2RefreshTokens::Cols::_scope = "\"scope\"";
const std::string Oauth2RefreshTokens::Cols::_expires_at = "\"expires_at\"";
const std::string Oauth2RefreshTokens::Cols::_revoked = "\"revoked\"";
const std::string Oauth2RefreshTokens::Cols::_revoked_at = "\"revoked_at\"";
const std::string Oauth2RefreshTokens::Cols::_revoked_by = "\"revoked_by\"";
const std::string Oauth2RefreshTokens::Cols::_family_id = "\"family_id\"";
const std::string Oauth2RefreshTokens::Cols::_org_id = "\"org_id\"";
const std::string Oauth2RefreshTokens::primaryKeyName = "token";
const bool Oauth2RefreshTokens::hasPrimaryKey = true;
const std::string Oauth2RefreshTokens::tableName = "\"oauth2_refresh_tokens\"";

const std::vector<typename Oauth2RefreshTokens::MetaData> Oauth2RefreshTokens::metaData_={
{"token","std::string","character varying",100,0,1,1},
{"access_token","std::string","character varying",100,0,0,1},
{"client_id","std::string","character varying",50,0,0,1},
{"user_id","std::string","character varying",50,0,0,0},
{"scope","std::string","text",0,0,0,0},
{"expires_at","int64_t","bigint",8,0,0,1},
{"revoked","bool","boolean",1,0,0,0},
{"revoked_at","int64_t","bigint",8,0,0,0},
{"revoked_by","std::string","character varying",50,0,0,0},
{"family_id","std::string","character varying",64,0,0,0},
{"org_id","int32_t","integer",4,0,0,0}
};
const std::string &Oauth2RefreshTokens::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Oauth2RefreshTokens::Oauth2RefreshTokens(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["token"].isNull())
        {
            token_=std::make_shared<std::string>(r["token"].as<std::string>());
        }
        if(!r["access_token"].isNull())
        {
            accessToken_=std::make_shared<std::string>(r["access_token"].as<std::string>());
        }
        if(!r["client_id"].isNull())
        {
            clientId_=std::make_shared<std::string>(r["client_id"].as<std::string>());
        }
        if(!r["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(r["user_id"].as<std::string>());
        }
        if(!r["scope"].isNull())
        {
            scope_=std::make_shared<std::string>(r["scope"].as<std::string>());
        }
        if(!r["expires_at"].isNull())
        {
            expiresAt_=std::make_shared<int64_t>(r["expires_at"].as<int64_t>());
        }
        if(!r["revoked"].isNull())
        {
            revoked_=std::make_shared<bool>(r["revoked"].as<bool>());
        }
        if(!r["revoked_at"].isNull())
        {
            revokedAt_=std::make_shared<int64_t>(r["revoked_at"].as<int64_t>());
        }
        if(!r["revoked_by"].isNull())
        {
            revokedBy_=std::make_shared<std::string>(r["revoked_by"].as<std::string>());
        }
        if(!r["family_id"].isNull())
        {
            familyId_=std::make_shared<std::string>(r["family_id"].as<std::string>());
        }
        if(!r["org_id"].isNull())
        {
            orgId_=std::make_shared<int32_t>(r["org_id"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 11 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            token_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            accessToken_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            clientId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            userId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            scope_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            expiresAt_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            revoked_=std::make_shared<bool>(r[index].as<bool>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            revokedAt_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            revokedBy_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            familyId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            orgId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

Oauth2RefreshTokens::Oauth2RefreshTokens(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 11)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            token_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            accessToken_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            clientId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            userId_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            scope_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            expiresAt_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            revoked_=std::make_shared<bool>(pJson[pMasqueradingVector[6]].asBool());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            revokedAt_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            revokedBy_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            familyId_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            orgId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[10]].asInt64());
        }
    }
}

Oauth2RefreshTokens::Oauth2RefreshTokens(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("token"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["token"].isNull())
        {
            token_=std::make_shared<std::string>(pJson["token"].asString());
        }
    }
    if(pJson.isMember("access_token"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["access_token"].isNull())
        {
            accessToken_=std::make_shared<std::string>(pJson["access_token"].asString());
        }
    }
    if(pJson.isMember("client_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["client_id"].isNull())
        {
            clientId_=std::make_shared<std::string>(pJson["client_id"].asString());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(pJson["user_id"].asString());
        }
    }
    if(pJson.isMember("scope"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["scope"].isNull())
        {
            scope_=std::make_shared<std::string>(pJson["scope"].asString());
        }
    }
    if(pJson.isMember("expires_at"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["expires_at"].isNull())
        {
            expiresAt_=std::make_shared<int64_t>((int64_t)pJson["expires_at"].asInt64());
        }
    }
    if(pJson.isMember("revoked"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["revoked"].isNull())
        {
            revoked_=std::make_shared<bool>(pJson["revoked"].asBool());
        }
    }
    if(pJson.isMember("revoked_at"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["revoked_at"].isNull())
        {
            revokedAt_=std::make_shared<int64_t>((int64_t)pJson["revoked_at"].asInt64());
        }
    }
    if(pJson.isMember("revoked_by"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["revoked_by"].isNull())
        {
            revokedBy_=std::make_shared<std::string>(pJson["revoked_by"].asString());
        }
    }
    if(pJson.isMember("family_id"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["family_id"].isNull())
        {
            familyId_=std::make_shared<std::string>(pJson["family_id"].asString());
        }
    }
    if(pJson.isMember("org_id"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["org_id"].isNull())
        {
            orgId_=std::make_shared<int32_t>((int32_t)pJson["org_id"].asInt64());
        }
    }
}

void Oauth2RefreshTokens::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 11)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            token_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            accessToken_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            clientId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            userId_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            scope_=std::make_shared<std::string>(pJson[pMasqueradingVector[4]].asString());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            expiresAt_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[5]].asInt64());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            revoked_=std::make_shared<bool>(pJson[pMasqueradingVector[6]].asBool());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            revokedAt_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[7]].asInt64());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            revokedBy_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            familyId_=std::make_shared<std::string>(pJson[pMasqueradingVector[9]].asString());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            orgId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[10]].asInt64());
        }
    }
}

void Oauth2RefreshTokens::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("token"))
    {
        if(!pJson["token"].isNull())
        {
            token_=std::make_shared<std::string>(pJson["token"].asString());
        }
    }
    if(pJson.isMember("access_token"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["access_token"].isNull())
        {
            accessToken_=std::make_shared<std::string>(pJson["access_token"].asString());
        }
    }
    if(pJson.isMember("client_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["client_id"].isNull())
        {
            clientId_=std::make_shared<std::string>(pJson["client_id"].asString());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(pJson["user_id"].asString());
        }
    }
    if(pJson.isMember("scope"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["scope"].isNull())
        {
            scope_=std::make_shared<std::string>(pJson["scope"].asString());
        }
    }
    if(pJson.isMember("expires_at"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["expires_at"].isNull())
        {
            expiresAt_=std::make_shared<int64_t>((int64_t)pJson["expires_at"].asInt64());
        }
    }
    if(pJson.isMember("revoked"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["revoked"].isNull())
        {
            revoked_=std::make_shared<bool>(pJson["revoked"].asBool());
        }
    }
    if(pJson.isMember("revoked_at"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["revoked_at"].isNull())
        {
            revokedAt_=std::make_shared<int64_t>((int64_t)pJson["revoked_at"].asInt64());
        }
    }
    if(pJson.isMember("revoked_by"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["revoked_by"].isNull())
        {
            revokedBy_=std::make_shared<std::string>(pJson["revoked_by"].asString());
        }
    }
    if(pJson.isMember("family_id"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["family_id"].isNull())
        {
            familyId_=std::make_shared<std::string>(pJson["family_id"].asString());
        }
    }
    if(pJson.isMember("org_id"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["org_id"].isNull())
        {
            orgId_=std::make_shared<int32_t>((int32_t)pJson["org_id"].asInt64());
        }
    }
}

const std::string &Oauth2RefreshTokens::getValueOfToken() const noexcept
{
    static const std::string defaultValue = std::string();
    if(token_)
        return *token_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Oauth2RefreshTokens::getToken() const noexcept
{
    return token_;
}
void Oauth2RefreshTokens::setToken(const std::string &pToken) noexcept
{
    token_ = std::make_shared<std::string>(pToken);
    dirtyFlag_[0] = true;
}
void Oauth2RefreshTokens::setToken(std::string &&pToken) noexcept
{
    token_ = std::make_shared<std::string>(std::move(pToken));
    dirtyFlag_[0] = true;
}
const typename Oauth2RefreshTokens::PrimaryKeyType & Oauth2RefreshTokens::getPrimaryKey() const
{
    assert(token_);
    return *token_;
}

const std::string &Oauth2RefreshTokens::getValueOfAccessToken() const noexcept
{
    static const std::string defaultValue = std::string();
    if(accessToken_)
        return *accessToken_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Oauth2RefreshTokens::getAccessToken() const noexcept
{
    return accessToken_;
}
void Oauth2RefreshTokens::setAccessToken(const std::string &pAccessToken) noexcept
{
    accessToken_ = std::make_shared<std::string>(pAccessToken);
    dirtyFlag_[1] = true;
}
void Oauth2RefreshTokens::setAccessToken(std::string &&pAccessToken) noexcept
{
    accessToken_ = std::make_shared<std::string>(std::move(pAccessToken));
    dirtyFlag_[1] = true;
}

const std::string &Oauth2RefreshTokens::getValueOfClientId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(clientId_)
        return *clientId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Oauth2RefreshTokens::getClientId() const noexcept
{
    return clientId_;
}
void Oauth2RefreshTokens::setClientId(const std::string &pClientId) noexcept
{
    clientId_ = std::make_shared<std::string>(pClientId);
    dirtyFlag_[2] = true;
}
void Oauth2RefreshTokens::setClientId(std::string &&pClientId) noexcept
{
    clientId_ = std::make_shared<std::string>(std::move(pClientId));
    dirtyFlag_[2] = true;
}

const std::string &Oauth2RefreshTokens::getValueOfUserId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(userId_)
        return *userId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Oauth2RefreshTokens::getUserId() const noexcept
{
    return userId_;
}
void Oauth2RefreshTokens::setUserId(const std::string &pUserId) noexcept
{
    userId_ = std::make_shared<std::string>(pUserId);
    dirtyFlag_[3] = true;
}
void Oauth2RefreshTokens::setUserId(std::string &&pUserId) noexcept
{
    userId_ = std::make_shared<std::string>(std::move(pUserId));
    dirtyFlag_[3] = true;
}
void Oauth2RefreshTokens::setUserIdToNull() noexcept
{
    userId_.reset();
    dirtyFlag_[3] = true;
}

const std::string &Oauth2RefreshTokens::getValueOfScope() const noexcept
{
    static const std::string defaultValue = std::string();
    if(scope_)
        return *scope_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Oauth2RefreshTokens::getScope() const noexcept
{
    return scope_;
}
void Oauth2RefreshTokens::setScope(const std::string &pScope) noexcept
{
    scope_ = std::make_shared<std::string>(pScope);
    dirtyFlag_[4] = true;
}
void Oauth2RefreshTokens::setScope(std::string &&pScope) noexcept
{
    scope_ = std::make_shared<std::string>(std::move(pScope));
    dirtyFlag_[4] = true;
}
void Oauth2RefreshTokens::setScopeToNull() noexcept
{
    scope_.reset();
    dirtyFlag_[4] = true;
}

const int64_t &Oauth2RefreshTokens::getValueOfExpiresAt() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(expiresAt_)
        return *expiresAt_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Oauth2RefreshTokens::getExpiresAt() const noexcept
{
    return expiresAt_;
}
void Oauth2RefreshTokens::setExpiresAt(const int64_t &pExpiresAt) noexcept
{
    expiresAt_ = std::make_shared<int64_t>(pExpiresAt);
    dirtyFlag_[5] = true;
}

const bool &Oauth2RefreshTokens::getValueOfRevoked() const noexcept
{
    static const bool defaultValue = bool();
    if(revoked_)
        return *revoked_;
    return defaultValue;
}
const std::shared_ptr<bool> &Oauth2RefreshTokens::getRevoked() const noexcept
{
    return revoked_;
}
void Oauth2RefreshTokens::setRevoked(const bool &pRevoked) noexcept
{
    revoked_ = std::make_shared<bool>(pRevoked);
    dirtyFlag_[6] = true;
}
void Oauth2RefreshTokens::setRevokedToNull() noexcept
{
    revoked_.reset();
    dirtyFlag_[6] = true;
}

const int64_t &Oauth2RefreshTokens::getValueOfRevokedAt() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(revokedAt_)
        return *revokedAt_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Oauth2RefreshTokens::getRevokedAt() const noexcept
{
    return revokedAt_;
}
void Oauth2RefreshTokens::setRevokedAt(const int64_t &pRevokedAt) noexcept
{
    revokedAt_ = std::make_shared<int64_t>(pRevokedAt);
    dirtyFlag_[7] = true;
}
void Oauth2RefreshTokens::setRevokedAtToNull() noexcept
{
    revokedAt_.reset();
    dirtyFlag_[7] = true;
}

const std::string &Oauth2RefreshTokens::getValueOfRevokedBy() const noexcept
{
    static const std::string defaultValue = std::string();
    if(revokedBy_)
        return *revokedBy_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Oauth2RefreshTokens::getRevokedBy() const noexcept
{
    return revokedBy_;
}
void Oauth2RefreshTokens::setRevokedBy(const std::string &pRevokedBy) noexcept
{
    revokedBy_ = std::make_shared<std::string>(pRevokedBy);
    dirtyFlag_[8] = true;
}
void Oauth2RefreshTokens::setRevokedBy(std::string &&pRevokedBy) noexcept
{
    revokedBy_ = std::make_shared<std::string>(std::move(pRevokedBy));
    dirtyFlag_[8] = true;
}
void Oauth2RefreshTokens::setRevokedByToNull() noexcept
{
    revokedBy_.reset();
    dirtyFlag_[8] = true;
}

const std::string &Oauth2RefreshTokens::getValueOfFamilyId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(familyId_)
        return *familyId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Oauth2RefreshTokens::getFamilyId() const noexcept
{
    return familyId_;
}
void Oauth2RefreshTokens::setFamilyId(const std::string &pFamilyId) noexcept
{
    familyId_ = std::make_shared<std::string>(pFamilyId);
    dirtyFlag_[9] = true;
}
void Oauth2RefreshTokens::setFamilyId(std::string &&pFamilyId) noexcept
{
    familyId_ = std::make_shared<std::string>(std::move(pFamilyId));
    dirtyFlag_[9] = true;
}
void Oauth2RefreshTokens::setFamilyIdToNull() noexcept
{
    familyId_.reset();
    dirtyFlag_[9] = true;
}

const int32_t &Oauth2RefreshTokens::getValueOfOrgId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(orgId_)
        return *orgId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Oauth2RefreshTokens::getOrgId() const noexcept
{
    return orgId_;
}
void Oauth2RefreshTokens::setOrgId(const int32_t &pOrgId) noexcept
{
    orgId_ = std::make_shared<int32_t>(pOrgId);
    dirtyFlag_[10] = true;
}
void Oauth2RefreshTokens::setOrgIdToNull() noexcept
{
    orgId_.reset();
    dirtyFlag_[10] = true;
}

void Oauth2RefreshTokens::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Oauth2RefreshTokens::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "token",
        "access_token",
        "client_id",
        "user_id",
        "scope",
        "expires_at",
        "revoked",
        "revoked_at",
        "revoked_by",
        "family_id",
        "org_id"
    };
    return inCols;
}

void Oauth2RefreshTokens::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getToken())
        {
            binder << getValueOfToken();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getAccessToken())
        {
            binder << getValueOfAccessToken();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getClientId())
        {
            binder << getValueOfClientId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getScope())
        {
            binder << getValueOfScope();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getExpiresAt())
        {
            binder << getValueOfExpiresAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getRevoked())
        {
            binder << getValueOfRevoked();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getRevokedAt())
        {
            binder << getValueOfRevokedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getRevokedBy())
        {
            binder << getValueOfRevokedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getFamilyId())
        {
            binder << getValueOfFamilyId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getOrgId())
        {
            binder << getValueOfOrgId();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Oauth2RefreshTokens::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    return ret;
}

void Oauth2RefreshTokens::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getToken())
        {
            binder << getValueOfToken();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getAccessToken())
        {
            binder << getValueOfAccessToken();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getClientId())
        {
            binder << getValueOfClientId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getScope())
        {
            binder << getValueOfScope();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getExpiresAt())
        {
            binder << getValueOfExpiresAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getRevoked())
        {
            binder << getValueOfRevoked();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getRevokedAt())
        {
            binder << getValueOfRevokedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getRevokedBy())
        {
            binder << getValueOfRevokedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getFamilyId())
        {
            binder << getValueOfFamilyId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getOrgId())
        {
            binder << getValueOfOrgId();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Oauth2RefreshTokens::toJson() const
{
    Json::Value ret;
    if(getToken())
    {
        ret["token"]=getValueOfToken();
    }
    else
    {
        ret["token"]=Json::Value();
    }
    if(getAccessToken())
    {
        ret["access_token"]=getValueOfAccessToken();
    }
    else
    {
        ret["access_token"]=Json::Value();
    }
    if(getClientId())
    {
        ret["client_id"]=getValueOfClientId();
    }
    else
    {
        ret["client_id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getScope())
    {
        ret["scope"]=getValueOfScope();
    }
    else
    {
        ret["scope"]=Json::Value();
    }
    if(getExpiresAt())
    {
        ret["expires_at"]=(Json::Int64)getValueOfExpiresAt();
    }
    else
    {
        ret["expires_at"]=Json::Value();
    }
    if(getRevoked())
    {
        ret["revoked"]=getValueOfRevoked();
    }
    else
    {
        ret["revoked"]=Json::Value();
    }
    if(getRevokedAt())
    {
        ret["revoked_at"]=(Json::Int64)getValueOfRevokedAt();
    }
    else
    {
        ret["revoked_at"]=Json::Value();
    }
    if(getRevokedBy())
    {
        ret["revoked_by"]=getValueOfRevokedBy();
    }
    else
    {
        ret["revoked_by"]=Json::Value();
    }
    if(getFamilyId())
    {
        ret["family_id"]=getValueOfFamilyId();
    }
    else
    {
        ret["family_id"]=Json::Value();
    }
    if(getOrgId())
    {
        ret["org_id"]=getValueOfOrgId();
    }
    else
    {
        ret["org_id"]=Json::Value();
    }
    return ret;
}

std::string Oauth2RefreshTokens::toString() const
{
    return toJson().toStyledString();
}

Json::Value Oauth2RefreshTokens::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 11)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getToken())
            {
                ret[pMasqueradingVector[0]]=getValueOfToken();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getAccessToken())
            {
                ret[pMasqueradingVector[1]]=getValueOfAccessToken();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getClientId())
            {
                ret[pMasqueradingVector[2]]=getValueOfClientId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getUserId())
            {
                ret[pMasqueradingVector[3]]=getValueOfUserId();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getScope())
            {
                ret[pMasqueradingVector[4]]=getValueOfScope();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getExpiresAt())
            {
                ret[pMasqueradingVector[5]]=(Json::Int64)getValueOfExpiresAt();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getRevoked())
            {
                ret[pMasqueradingVector[6]]=getValueOfRevoked();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getRevokedAt())
            {
                ret[pMasqueradingVector[7]]=(Json::Int64)getValueOfRevokedAt();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getRevokedBy())
            {
                ret[pMasqueradingVector[8]]=getValueOfRevokedBy();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getFamilyId())
            {
                ret[pMasqueradingVector[9]]=getValueOfFamilyId();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getOrgId())
            {
                ret[pMasqueradingVector[10]]=getValueOfOrgId();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getToken())
    {
        ret["token"]=getValueOfToken();
    }
    else
    {
        ret["token"]=Json::Value();
    }
    if(getAccessToken())
    {
        ret["access_token"]=getValueOfAccessToken();
    }
    else
    {
        ret["access_token"]=Json::Value();
    }
    if(getClientId())
    {
        ret["client_id"]=getValueOfClientId();
    }
    else
    {
        ret["client_id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getScope())
    {
        ret["scope"]=getValueOfScope();
    }
    else
    {
        ret["scope"]=Json::Value();
    }
    if(getExpiresAt())
    {
        ret["expires_at"]=(Json::Int64)getValueOfExpiresAt();
    }
    else
    {
        ret["expires_at"]=Json::Value();
    }
    if(getRevoked())
    {
        ret["revoked"]=getValueOfRevoked();
    }
    else
    {
        ret["revoked"]=Json::Value();
    }
    if(getRevokedAt())
    {
        ret["revoked_at"]=(Json::Int64)getValueOfRevokedAt();
    }
    else
    {
        ret["revoked_at"]=Json::Value();
    }
    if(getRevokedBy())
    {
        ret["revoked_by"]=getValueOfRevokedBy();
    }
    else
    {
        ret["revoked_by"]=Json::Value();
    }
    if(getFamilyId())
    {
        ret["family_id"]=getValueOfFamilyId();
    }
    else
    {
        ret["family_id"]=Json::Value();
    }
    if(getOrgId())
    {
        ret["org_id"]=getValueOfOrgId();
    }
    else
    {
        ret["org_id"]=Json::Value();
    }
    return ret;
}

bool Oauth2RefreshTokens::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("token"))
    {
        if(!validJsonOfField(0, "token", pJson["token"], err, true))
            return false;
    }
    else
    {
        err="The token column cannot be null";
        return false;
    }
    if(pJson.isMember("access_token"))
    {
        if(!validJsonOfField(1, "access_token", pJson["access_token"], err, true))
            return false;
    }
    else
    {
        err="The access_token column cannot be null";
        return false;
    }
    if(pJson.isMember("client_id"))
    {
        if(!validJsonOfField(2, "client_id", pJson["client_id"], err, true))
            return false;
    }
    else
    {
        err="The client_id column cannot be null";
        return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(3, "user_id", pJson["user_id"], err, true))
            return false;
    }
    if(pJson.isMember("scope"))
    {
        if(!validJsonOfField(4, "scope", pJson["scope"], err, true))
            return false;
    }
    if(pJson.isMember("expires_at"))
    {
        if(!validJsonOfField(5, "expires_at", pJson["expires_at"], err, true))
            return false;
    }
    else
    {
        err="The expires_at column cannot be null";
        return false;
    }
    if(pJson.isMember("revoked"))
    {
        if(!validJsonOfField(6, "revoked", pJson["revoked"], err, true))
            return false;
    }
    if(pJson.isMember("revoked_at"))
    {
        if(!validJsonOfField(7, "revoked_at", pJson["revoked_at"], err, true))
            return false;
    }
    if(pJson.isMember("revoked_by"))
    {
        if(!validJsonOfField(8, "revoked_by", pJson["revoked_by"], err, true))
            return false;
    }
    if(pJson.isMember("family_id"))
    {
        if(!validJsonOfField(9, "family_id", pJson["family_id"], err, true))
            return false;
    }
    if(pJson.isMember("org_id"))
    {
        if(!validJsonOfField(10, "org_id", pJson["org_id"], err, true))
            return false;
    }
    return true;
}
bool Oauth2RefreshTokens::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                             const std::vector<std::string> &pMasqueradingVector,
                                                             std::string &err)
{
    if(pMasqueradingVector.size() != 11)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[5] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Oauth2RefreshTokens::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("token"))
    {
        if(!validJsonOfField(0, "token", pJson["token"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("access_token"))
    {
        if(!validJsonOfField(1, "access_token", pJson["access_token"], err, false))
            return false;
    }
    if(pJson.isMember("client_id"))
    {
        if(!validJsonOfField(2, "client_id", pJson["client_id"], err, false))
            return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(3, "user_id", pJson["user_id"], err, false))
            return false;
    }
    if(pJson.isMember("scope"))
    {
        if(!validJsonOfField(4, "scope", pJson["scope"], err, false))
            return false;
    }
    if(pJson.isMember("expires_at"))
    {
        if(!validJsonOfField(5, "expires_at", pJson["expires_at"], err, false))
            return false;
    }
    if(pJson.isMember("revoked"))
    {
        if(!validJsonOfField(6, "revoked", pJson["revoked"], err, false))
            return false;
    }
    if(pJson.isMember("revoked_at"))
    {
        if(!validJsonOfField(7, "revoked_at", pJson["revoked_at"], err, false))
            return false;
    }
    if(pJson.isMember("revoked_by"))
    {
        if(!validJsonOfField(8, "revoked_by", pJson["revoked_by"], err, false))
            return false;
    }
    if(pJson.isMember("family_id"))
    {
        if(!validJsonOfField(9, "family_id", pJson["family_id"], err, false))
            return false;
    }
    if(pJson.isMember("org_id"))
    {
        if(!validJsonOfField(10, "org_id", pJson["org_id"], err, false))
            return false;
    }
    return true;
}
bool Oauth2RefreshTokens::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                           const std::vector<std::string> &pMasqueradingVector,
                                                           std::string &err)
{
    if(pMasqueradingVector.size() != 11)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Oauth2RefreshTokens::validJsonOfField(size_t index,
                                           const std::string &fieldName,
                                           const Json::Value &pJson,
                                           std::string &err,
                                           bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 100)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 100)";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 100)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 100)";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 64)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 64)";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
Oauth2Clients Oauth2RefreshTokens::getClient(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from oauth2_clients where client_id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *clientId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return Oauth2Clients(r[0]);
}

void Oauth2RefreshTokens::getClient(const DbClientPtr &clientPtr,
                                    const std::function<void(Oauth2Clients)> &rcb,
                                    const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from oauth2_clients where client_id = $1";
    *clientPtr << sql
               << *clientId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Oauth2Clients(r[0]));
                    }
               }
               >> ecb;
}
Organizations Oauth2RefreshTokens::getOrganizations(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from organizations where id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *orgId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return Organizations(r[0]);
}

void Oauth2RefreshTokens::getOrganizations(const DbClientPtr &clientPtr,
                                           const std::function<void(Organizations)> &rcb,
                                           const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from organizations where id = $1";
    *clientPtr << sql
               << *orgId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Organizations(r[0]));
                    }
               }
               >> ecb;
}
