/**
 *
 *  Oauth2AccessTokens.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "Oauth2AccessTokens.h"
#include "Oauth2Clients.h"
#include "Organizations.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::fulla_db;

const std::string Oauth2AccessTokens::Cols::_token = "\"token\"";
const std::string Oauth2AccessTokens::Cols::_client_id = "\"client_id\"";
const std::string Oauth2AccessTokens::Cols::_user_id = "\"user_id\"";
const std::string Oauth2AccessTokens::Cols::_scope = "\"scope\"";
const std::string Oauth2AccessTokens::Cols::_expires_at = "\"expires_at\"";
const std::string Oauth2AccessTokens::Cols::_revoked = "\"revoked\"";
const std::string Oauth2AccessTokens::Cols::_issued_at = "\"issued_at\"";
const std::string Oauth2AccessTokens::Cols::_issuer = "\"issuer\"";
const std::string Oauth2AccessTokens::Cols::_audience = "\"audience\"";
const std::string Oauth2AccessTokens::Cols::_not_before = "\"not_before\"";
const std::string Oauth2AccessTokens::Cols::_introspect_count = "\"introspect_count\"";
const std::string Oauth2AccessTokens::Cols::_revoked_at = "\"revoked_at\"";
const std::string Oauth2AccessTokens::Cols::_revoked_by = "\"revoked_by\"";
const std::string Oauth2AccessTokens::Cols::_org_id = "\"org_id\"";
const std::string Oauth2AccessTokens::primaryKeyName = "token";
const bool Oauth2AccessTokens::hasPrimaryKey = true;
const std::string Oauth2AccessTokens::tableName = "\"oauth2_access_tokens\"";

const std::vector<typename Oauth2AccessTokens::MetaData> Oauth2AccessTokens::metaData_={
{"token","std::string","character varying",100,0,1,1},
{"client_id","std::string","character varying",50,0,0,1},
{"user_id","std::string","character varying",50,0,0,0},
{"scope","std::string","text",0,0,0,0},
{"expires_at","int64_t","bigint",8,0,0,1},
{"revoked","bool","boolean",1,0,0,0},
{"issued_at","int64_t","bigint",8,0,0,1},
{"issuer","std::string","character varying",255,0,0,1},
{"audience","std::string","character varying",255,0,0,0},
{"not_before","int64_t","bigint",8,0,0,0},
{"introspect_count","int32_t","integer",4,0,0,0},
{"revoked_at","int64_t","bigint",8,0,0,0},
{"revoked_by","std::string","character varying",50,0,0,0},
{"org_id","int32_t","integer",4,0,0,0}
};
const std::string &Oauth2AccessTokens::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
Oauth2AccessTokens::Oauth2AccessTokens(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["token"].isNull())
        {
            token_=std::make_shared<std::string>(r["token"].as<std::string>());
        }
        if(!r["client_id"].isNull())
        {
            clientId_=std::make_shared<std::string>(r["client_id"].as<std::string>());
        }
        if(!r["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(r["user_id"].as<std::string>());
        }
        if(!r["scope"].isNull())
        {
            scope_=std::make_shared<std::string>(r["scope"].as<std::string>());
        }
        if(!r["expires_at"].isNull())
        {
            expiresAt_=std::make_shared<int64_t>(r["expires_at"].as<int64_t>());
        }
        if(!r["revoked"].isNull())
        {
            revoked_=std::make_shared<bool>(r["revoked"].as<bool>());
        }
        if(!r["issued_at"].isNull())
        {
            issuedAt_=std::make_shared<int64_t>(r["issued_at"].as<int64_t>());
        }
        if(!r["issuer"].isNull())
        {
            issuer_=std::make_shared<std::string>(r["issuer"].as<std::string>());
        }
        if(!r["audience"].isNull())
        {
            audience_=std::make_shared<std::string>(r["audience"].as<std::string>());
        }
        if(!r["not_before"].isNull())
        {
            notBefore_=std::make_shared<int64_t>(r["not_before"].as<int64_t>());
        }
        if(!r["introspect_count"].isNull())
        {
            introspectCount_=std::make_shared<int32_t>(r["introspect_count"].as<int32_t>());
        }
        if(!r["revoked_at"].isNull())
        {
            revokedAt_=std::make_shared<int64_t>(r["revoked_at"].as<int64_t>());
        }
        if(!r["revoked_by"].isNull())
        {
            revokedBy_=std::make_shared<std::string>(r["revoked_by"].as<std::string>());
        }
        if(!r["org_id"].isNull())
        {
            orgId_=std::make_shared<int32_t>(r["org_id"].as<int32_t>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 14 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            token_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            clientId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            userId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            scope_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            expiresAt_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            revoked_=std::make_shared<bool>(r[index].as<bool>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            issuedAt_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            issuer_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            audience_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 9;
        if(!r[index].isNull())
        {
            notBefore_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 10;
        if(!r[index].isNull())
        {
            introspectCount_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 11;
        if(!r[index].isNull())
        {
            revokedAt_=std::make_shared<int64_t>(r[index].as<int64_t>());
        }
        index = offset + 12;
        if(!r[index].isNull())
        {
            revokedBy_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 13;
        if(!r[index].isNull())
        {
            orgId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
    }

}

Oauth2AccessTokens::Oauth2AccessTokens(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 14)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            token_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            clientId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            userId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            scope_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            expiresAt_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            revoked_=std::make_shared<bool>(pJson[pMasqueradingVector[5]].asBool());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            issuedAt_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            issuer_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            audience_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            notBefore_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[9]].asInt64());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            introspectCount_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[10]].asInt64());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            revokedAt_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[11]].asInt64());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            revokedBy_=std::make_shared<std::string>(pJson[pMasqueradingVector[12]].asString());
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            orgId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[13]].asInt64());
        }
    }
}

Oauth2AccessTokens::Oauth2AccessTokens(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("token"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["token"].isNull())
        {
            token_=std::make_shared<std::string>(pJson["token"].asString());
        }
    }
    if(pJson.isMember("client_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["client_id"].isNull())
        {
            clientId_=std::make_shared<std::string>(pJson["client_id"].asString());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(pJson["user_id"].asString());
        }
    }
    if(pJson.isMember("scope"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["scope"].isNull())
        {
            scope_=std::make_shared<std::string>(pJson["scope"].asString());
        }
    }
    if(pJson.isMember("expires_at"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["expires_at"].isNull())
        {
            expiresAt_=std::make_shared<int64_t>((int64_t)pJson["expires_at"].asInt64());
        }
    }
    if(pJson.isMember("revoked"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["revoked"].isNull())
        {
            revoked_=std::make_shared<bool>(pJson["revoked"].asBool());
        }
    }
    if(pJson.isMember("issued_at"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["issued_at"].isNull())
        {
            issuedAt_=std::make_shared<int64_t>((int64_t)pJson["issued_at"].asInt64());
        }
    }
    if(pJson.isMember("issuer"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["issuer"].isNull())
        {
            issuer_=std::make_shared<std::string>(pJson["issuer"].asString());
        }
    }
    if(pJson.isMember("audience"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["audience"].isNull())
        {
            audience_=std::make_shared<std::string>(pJson["audience"].asString());
        }
    }
    if(pJson.isMember("not_before"))
    {
        dirtyFlag_[9]=true;
        if(!pJson["not_before"].isNull())
        {
            notBefore_=std::make_shared<int64_t>((int64_t)pJson["not_before"].asInt64());
        }
    }
    if(pJson.isMember("introspect_count"))
    {
        dirtyFlag_[10]=true;
        if(!pJson["introspect_count"].isNull())
        {
            introspectCount_=std::make_shared<int32_t>((int32_t)pJson["introspect_count"].asInt64());
        }
    }
    if(pJson.isMember("revoked_at"))
    {
        dirtyFlag_[11]=true;
        if(!pJson["revoked_at"].isNull())
        {
            revokedAt_=std::make_shared<int64_t>((int64_t)pJson["revoked_at"].asInt64());
        }
    }
    if(pJson.isMember("revoked_by"))
    {
        dirtyFlag_[12]=true;
        if(!pJson["revoked_by"].isNull())
        {
            revokedBy_=std::make_shared<std::string>(pJson["revoked_by"].asString());
        }
    }
    if(pJson.isMember("org_id"))
    {
        dirtyFlag_[13]=true;
        if(!pJson["org_id"].isNull())
        {
            orgId_=std::make_shared<int32_t>((int32_t)pJson["org_id"].asInt64());
        }
    }
}

void Oauth2AccessTokens::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 14)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            token_=std::make_shared<std::string>(pJson[pMasqueradingVector[0]].asString());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            clientId_=std::make_shared<std::string>(pJson[pMasqueradingVector[1]].asString());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            userId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            scope_=std::make_shared<std::string>(pJson[pMasqueradingVector[3]].asString());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            expiresAt_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[4]].asInt64());
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            revoked_=std::make_shared<bool>(pJson[pMasqueradingVector[5]].asBool());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            issuedAt_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            issuer_=std::make_shared<std::string>(pJson[pMasqueradingVector[7]].asString());
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            audience_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
    if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
    {
        dirtyFlag_[9] = true;
        if(!pJson[pMasqueradingVector[9]].isNull())
        {
            notBefore_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[9]].asInt64());
        }
    }
    if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
    {
        dirtyFlag_[10] = true;
        if(!pJson[pMasqueradingVector[10]].isNull())
        {
            introspectCount_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[10]].asInt64());
        }
    }
    if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
    {
        dirtyFlag_[11] = true;
        if(!pJson[pMasqueradingVector[11]].isNull())
        {
            revokedAt_=std::make_shared<int64_t>((int64_t)pJson[pMasqueradingVector[11]].asInt64());
        }
    }
    if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
    {
        dirtyFlag_[12] = true;
        if(!pJson[pMasqueradingVector[12]].isNull())
        {
            revokedBy_=std::make_shared<std::string>(pJson[pMasqueradingVector[12]].asString());
        }
    }
    if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
    {
        dirtyFlag_[13] = true;
        if(!pJson[pMasqueradingVector[13]].isNull())
        {
            orgId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[13]].asInt64());
        }
    }
}

void Oauth2AccessTokens::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("token"))
    {
        if(!pJson["token"].isNull())
        {
            token_=std::make_shared<std::string>(pJson["token"].asString());
        }
    }
    if(pJson.isMember("client_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["client_id"].isNull())
        {
            clientId_=std::make_shared<std::string>(pJson["client_id"].asString());
        }
    }
    if(pJson.isMember("user_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["user_id"].isNull())
        {
            userId_=std::make_shared<std::string>(pJson["user_id"].asString());
        }
    }
    if(pJson.isMember("scope"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["scope"].isNull())
        {
            scope_=std::make_shared<std::string>(pJson["scope"].asString());
        }
    }
    if(pJson.isMember("expires_at"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["expires_at"].isNull())
        {
            expiresAt_=std::make_shared<int64_t>((int64_t)pJson["expires_at"].asInt64());
        }
    }
    if(pJson.isMember("revoked"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["revoked"].isNull())
        {
            revoked_=std::make_shared<bool>(pJson["revoked"].asBool());
        }
    }
    if(pJson.isMember("issued_at"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["issued_at"].isNull())
        {
            issuedAt_=std::make_shared<int64_t>((int64_t)pJson["issued_at"].asInt64());
        }
    }
    if(pJson.isMember("issuer"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["issuer"].isNull())
        {
            issuer_=std::make_shared<std::string>(pJson["issuer"].asString());
        }
    }
    if(pJson.isMember("audience"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["audience"].isNull())
        {
            audience_=std::make_shared<std::string>(pJson["audience"].asString());
        }
    }
    if(pJson.isMember("not_before"))
    {
        dirtyFlag_[9] = true;
        if(!pJson["not_before"].isNull())
        {
            notBefore_=std::make_shared<int64_t>((int64_t)pJson["not_before"].asInt64());
        }
    }
    if(pJson.isMember("introspect_count"))
    {
        dirtyFlag_[10] = true;
        if(!pJson["introspect_count"].isNull())
        {
            introspectCount_=std::make_shared<int32_t>((int32_t)pJson["introspect_count"].asInt64());
        }
    }
    if(pJson.isMember("revoked_at"))
    {
        dirtyFlag_[11] = true;
        if(!pJson["revoked_at"].isNull())
        {
            revokedAt_=std::make_shared<int64_t>((int64_t)pJson["revoked_at"].asInt64());
        }
    }
    if(pJson.isMember("revoked_by"))
    {
        dirtyFlag_[12] = true;
        if(!pJson["revoked_by"].isNull())
        {
            revokedBy_=std::make_shared<std::string>(pJson["revoked_by"].asString());
        }
    }
    if(pJson.isMember("org_id"))
    {
        dirtyFlag_[13] = true;
        if(!pJson["org_id"].isNull())
        {
            orgId_=std::make_shared<int32_t>((int32_t)pJson["org_id"].asInt64());
        }
    }
}

const std::string &Oauth2AccessTokens::getValueOfToken() const noexcept
{
    static const std::string defaultValue = std::string();
    if(token_)
        return *token_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Oauth2AccessTokens::getToken() const noexcept
{
    return token_;
}
void Oauth2AccessTokens::setToken(const std::string &pToken) noexcept
{
    token_ = std::make_shared<std::string>(pToken);
    dirtyFlag_[0] = true;
}
void Oauth2AccessTokens::setToken(std::string &&pToken) noexcept
{
    token_ = std::make_shared<std::string>(std::move(pToken));
    dirtyFlag_[0] = true;
}
const typename Oauth2AccessTokens::PrimaryKeyType & Oauth2AccessTokens::getPrimaryKey() const
{
    assert(token_);
    return *token_;
}

const std::string &Oauth2AccessTokens::getValueOfClientId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(clientId_)
        return *clientId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Oauth2AccessTokens::getClientId() const noexcept
{
    return clientId_;
}
void Oauth2AccessTokens::setClientId(const std::string &pClientId) noexcept
{
    clientId_ = std::make_shared<std::string>(pClientId);
    dirtyFlag_[1] = true;
}
void Oauth2AccessTokens::setClientId(std::string &&pClientId) noexcept
{
    clientId_ = std::make_shared<std::string>(std::move(pClientId));
    dirtyFlag_[1] = true;
}

const std::string &Oauth2AccessTokens::getValueOfUserId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(userId_)
        return *userId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Oauth2AccessTokens::getUserId() const noexcept
{
    return userId_;
}
void Oauth2AccessTokens::setUserId(const std::string &pUserId) noexcept
{
    userId_ = std::make_shared<std::string>(pUserId);
    dirtyFlag_[2] = true;
}
void Oauth2AccessTokens::setUserId(std::string &&pUserId) noexcept
{
    userId_ = std::make_shared<std::string>(std::move(pUserId));
    dirtyFlag_[2] = true;
}
void Oauth2AccessTokens::setUserIdToNull() noexcept
{
    userId_.reset();
    dirtyFlag_[2] = true;
}

const std::string &Oauth2AccessTokens::getValueOfScope() const noexcept
{
    static const std::string defaultValue = std::string();
    if(scope_)
        return *scope_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Oauth2AccessTokens::getScope() const noexcept
{
    return scope_;
}
void Oauth2AccessTokens::setScope(const std::string &pScope) noexcept
{
    scope_ = std::make_shared<std::string>(pScope);
    dirtyFlag_[3] = true;
}
void Oauth2AccessTokens::setScope(std::string &&pScope) noexcept
{
    scope_ = std::make_shared<std::string>(std::move(pScope));
    dirtyFlag_[3] = true;
}
void Oauth2AccessTokens::setScopeToNull() noexcept
{
    scope_.reset();
    dirtyFlag_[3] = true;
}

const int64_t &Oauth2AccessTokens::getValueOfExpiresAt() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(expiresAt_)
        return *expiresAt_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Oauth2AccessTokens::getExpiresAt() const noexcept
{
    return expiresAt_;
}
void Oauth2AccessTokens::setExpiresAt(const int64_t &pExpiresAt) noexcept
{
    expiresAt_ = std::make_shared<int64_t>(pExpiresAt);
    dirtyFlag_[4] = true;
}

const bool &Oauth2AccessTokens::getValueOfRevoked() const noexcept
{
    static const bool defaultValue = bool();
    if(revoked_)
        return *revoked_;
    return defaultValue;
}
const std::shared_ptr<bool> &Oauth2AccessTokens::getRevoked() const noexcept
{
    return revoked_;
}
void Oauth2AccessTokens::setRevoked(const bool &pRevoked) noexcept
{
    revoked_ = std::make_shared<bool>(pRevoked);
    dirtyFlag_[5] = true;
}
void Oauth2AccessTokens::setRevokedToNull() noexcept
{
    revoked_.reset();
    dirtyFlag_[5] = true;
}

const int64_t &Oauth2AccessTokens::getValueOfIssuedAt() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(issuedAt_)
        return *issuedAt_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Oauth2AccessTokens::getIssuedAt() const noexcept
{
    return issuedAt_;
}
void Oauth2AccessTokens::setIssuedAt(const int64_t &pIssuedAt) noexcept
{
    issuedAt_ = std::make_shared<int64_t>(pIssuedAt);
    dirtyFlag_[6] = true;
}

const std::string &Oauth2AccessTokens::getValueOfIssuer() const noexcept
{
    static const std::string defaultValue = std::string();
    if(issuer_)
        return *issuer_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Oauth2AccessTokens::getIssuer() const noexcept
{
    return issuer_;
}
void Oauth2AccessTokens::setIssuer(const std::string &pIssuer) noexcept
{
    issuer_ = std::make_shared<std::string>(pIssuer);
    dirtyFlag_[7] = true;
}
void Oauth2AccessTokens::setIssuer(std::string &&pIssuer) noexcept
{
    issuer_ = std::make_shared<std::string>(std::move(pIssuer));
    dirtyFlag_[7] = true;
}

const std::string &Oauth2AccessTokens::getValueOfAudience() const noexcept
{
    static const std::string defaultValue = std::string();
    if(audience_)
        return *audience_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Oauth2AccessTokens::getAudience() const noexcept
{
    return audience_;
}
void Oauth2AccessTokens::setAudience(const std::string &pAudience) noexcept
{
    audience_ = std::make_shared<std::string>(pAudience);
    dirtyFlag_[8] = true;
}
void Oauth2AccessTokens::setAudience(std::string &&pAudience) noexcept
{
    audience_ = std::make_shared<std::string>(std::move(pAudience));
    dirtyFlag_[8] = true;
}
void Oauth2AccessTokens::setAudienceToNull() noexcept
{
    audience_.reset();
    dirtyFlag_[8] = true;
}

const int64_t &Oauth2AccessTokens::getValueOfNotBefore() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(notBefore_)
        return *notBefore_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Oauth2AccessTokens::getNotBefore() const noexcept
{
    return notBefore_;
}
void Oauth2AccessTokens::setNotBefore(const int64_t &pNotBefore) noexcept
{
    notBefore_ = std::make_shared<int64_t>(pNotBefore);
    dirtyFlag_[9] = true;
}
void Oauth2AccessTokens::setNotBeforeToNull() noexcept
{
    notBefore_.reset();
    dirtyFlag_[9] = true;
}

const int32_t &Oauth2AccessTokens::getValueOfIntrospectCount() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(introspectCount_)
        return *introspectCount_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Oauth2AccessTokens::getIntrospectCount() const noexcept
{
    return introspectCount_;
}
void Oauth2AccessTokens::setIntrospectCount(const int32_t &pIntrospectCount) noexcept
{
    introspectCount_ = std::make_shared<int32_t>(pIntrospectCount);
    dirtyFlag_[10] = true;
}
void Oauth2AccessTokens::setIntrospectCountToNull() noexcept
{
    introspectCount_.reset();
    dirtyFlag_[10] = true;
}

const int64_t &Oauth2AccessTokens::getValueOfRevokedAt() const noexcept
{
    static const int64_t defaultValue = int64_t();
    if(revokedAt_)
        return *revokedAt_;
    return defaultValue;
}
const std::shared_ptr<int64_t> &Oauth2AccessTokens::getRevokedAt() const noexcept
{
    return revokedAt_;
}
void Oauth2AccessTokens::setRevokedAt(const int64_t &pRevokedAt) noexcept
{
    revokedAt_ = std::make_shared<int64_t>(pRevokedAt);
    dirtyFlag_[11] = true;
}
void Oauth2AccessTokens::setRevokedAtToNull() noexcept
{
    revokedAt_.reset();
    dirtyFlag_[11] = true;
}

const std::string &Oauth2AccessTokens::getValueOfRevokedBy() const noexcept
{
    static const std::string defaultValue = std::string();
    if(revokedBy_)
        return *revokedBy_;
    return defaultValue;
}
const std::shared_ptr<std::string> &Oauth2AccessTokens::getRevokedBy() const noexcept
{
    return revokedBy_;
}
void Oauth2AccessTokens::setRevokedBy(const std::string &pRevokedBy) noexcept
{
    revokedBy_ = std::make_shared<std::string>(pRevokedBy);
    dirtyFlag_[12] = true;
}
void Oauth2AccessTokens::setRevokedBy(std::string &&pRevokedBy) noexcept
{
    revokedBy_ = std::make_shared<std::string>(std::move(pRevokedBy));
    dirtyFlag_[12] = true;
}
void Oauth2AccessTokens::setRevokedByToNull() noexcept
{
    revokedBy_.reset();
    dirtyFlag_[12] = true;
}

const int32_t &Oauth2AccessTokens::getValueOfOrgId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(orgId_)
        return *orgId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &Oauth2AccessTokens::getOrgId() const noexcept
{
    return orgId_;
}
void Oauth2AccessTokens::setOrgId(const int32_t &pOrgId) noexcept
{
    orgId_ = std::make_shared<int32_t>(pOrgId);
    dirtyFlag_[13] = true;
}
void Oauth2AccessTokens::setOrgIdToNull() noexcept
{
    orgId_.reset();
    dirtyFlag_[13] = true;
}

void Oauth2AccessTokens::updateId(const uint64_t id)
{
}

const std::vector<std::string> &Oauth2AccessTokens::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "token",
        "client_id",
        "user_id",
        "scope",
        "expires_at",
        "revoked",
        "issued_at",
        "issuer",
        "audience",
        "not_before",
        "introspect_count",
        "revoked_at",
        "revoked_by",
        "org_id"
    };
    return inCols;
}

void Oauth2AccessTokens::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getToken())
        {
            binder << getValueOfToken();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getClientId())
        {
            binder << getValueOfClientId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getScope())
        {
            binder << getValueOfScope();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getExpiresAt())
        {
            binder << getValueOfExpiresAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getRevoked())
        {
            binder << getValueOfRevoked();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getIssuedAt())
        {
            binder << getValueOfIssuedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getIssuer())
        {
            binder << getValueOfIssuer();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getAudience())
        {
            binder << getValueOfAudience();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getNotBefore())
        {
            binder << getValueOfNotBefore();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getIntrospectCount())
        {
            binder << getValueOfIntrospectCount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getRevokedAt())
        {
            binder << getValueOfRevokedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getRevokedBy())
        {
            binder << getValueOfRevokedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getOrgId())
        {
            binder << getValueOfOrgId();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> Oauth2AccessTokens::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[0])
    {
        ret.push_back(getColumnName(0));
    }
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    if(dirtyFlag_[9])
    {
        ret.push_back(getColumnName(9));
    }
    if(dirtyFlag_[10])
    {
        ret.push_back(getColumnName(10));
    }
    if(dirtyFlag_[11])
    {
        ret.push_back(getColumnName(11));
    }
    if(dirtyFlag_[12])
    {
        ret.push_back(getColumnName(12));
    }
    if(dirtyFlag_[13])
    {
        ret.push_back(getColumnName(13));
    }
    return ret;
}

void Oauth2AccessTokens::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[0])
    {
        if(getToken())
        {
            binder << getValueOfToken();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[1])
    {
        if(getClientId())
        {
            binder << getValueOfClientId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getUserId())
        {
            binder << getValueOfUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getScope())
        {
            binder << getValueOfScope();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getExpiresAt())
        {
            binder << getValueOfExpiresAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getRevoked())
        {
            binder << getValueOfRevoked();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getIssuedAt())
        {
            binder << getValueOfIssuedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getIssuer())
        {
            binder << getValueOfIssuer();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getAudience())
        {
            binder << getValueOfAudience();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[9])
    {
        if(getNotBefore())
        {
            binder << getValueOfNotBefore();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[10])
    {
        if(getIntrospectCount())
        {
            binder << getValueOfIntrospectCount();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[11])
    {
        if(getRevokedAt())
        {
            binder << getValueOfRevokedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[12])
    {
        if(getRevokedBy())
        {
            binder << getValueOfRevokedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[13])
    {
        if(getOrgId())
        {
            binder << getValueOfOrgId();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value Oauth2AccessTokens::toJson() const
{
    Json::Value ret;
    if(getToken())
    {
        ret["token"]=getValueOfToken();
    }
    else
    {
        ret["token"]=Json::Value();
    }
    if(getClientId())
    {
        ret["client_id"]=getValueOfClientId();
    }
    else
    {
        ret["client_id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getScope())
    {
        ret["scope"]=getValueOfScope();
    }
    else
    {
        ret["scope"]=Json::Value();
    }
    if(getExpiresAt())
    {
        ret["expires_at"]=(Json::Int64)getValueOfExpiresAt();
    }
    else
    {
        ret["expires_at"]=Json::Value();
    }
    if(getRevoked())
    {
        ret["revoked"]=getValueOfRevoked();
    }
    else
    {
        ret["revoked"]=Json::Value();
    }
    if(getIssuedAt())
    {
        ret["issued_at"]=(Json::Int64)getValueOfIssuedAt();
    }
    else
    {
        ret["issued_at"]=Json::Value();
    }
    if(getIssuer())
    {
        ret["issuer"]=getValueOfIssuer();
    }
    else
    {
        ret["issuer"]=Json::Value();
    }
    if(getAudience())
    {
        ret["audience"]=getValueOfAudience();
    }
    else
    {
        ret["audience"]=Json::Value();
    }
    if(getNotBefore())
    {
        ret["not_before"]=(Json::Int64)getValueOfNotBefore();
    }
    else
    {
        ret["not_before"]=Json::Value();
    }
    if(getIntrospectCount())
    {
        ret["introspect_count"]=getValueOfIntrospectCount();
    }
    else
    {
        ret["introspect_count"]=Json::Value();
    }
    if(getRevokedAt())
    {
        ret["revoked_at"]=(Json::Int64)getValueOfRevokedAt();
    }
    else
    {
        ret["revoked_at"]=Json::Value();
    }
    if(getRevokedBy())
    {
        ret["revoked_by"]=getValueOfRevokedBy();
    }
    else
    {
        ret["revoked_by"]=Json::Value();
    }
    if(getOrgId())
    {
        ret["org_id"]=getValueOfOrgId();
    }
    else
    {
        ret["org_id"]=Json::Value();
    }
    return ret;
}

std::string Oauth2AccessTokens::toString() const
{
    return toJson().toStyledString();
}

Json::Value Oauth2AccessTokens::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 14)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getToken())
            {
                ret[pMasqueradingVector[0]]=getValueOfToken();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getClientId())
            {
                ret[pMasqueradingVector[1]]=getValueOfClientId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getUserId())
            {
                ret[pMasqueradingVector[2]]=getValueOfUserId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getScope())
            {
                ret[pMasqueradingVector[3]]=getValueOfScope();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getExpiresAt())
            {
                ret[pMasqueradingVector[4]]=(Json::Int64)getValueOfExpiresAt();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getRevoked())
            {
                ret[pMasqueradingVector[5]]=getValueOfRevoked();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getIssuedAt())
            {
                ret[pMasqueradingVector[6]]=(Json::Int64)getValueOfIssuedAt();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getIssuer())
            {
                ret[pMasqueradingVector[7]]=getValueOfIssuer();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getAudience())
            {
                ret[pMasqueradingVector[8]]=getValueOfAudience();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[9].empty())
        {
            if(getNotBefore())
            {
                ret[pMasqueradingVector[9]]=(Json::Int64)getValueOfNotBefore();
            }
            else
            {
                ret[pMasqueradingVector[9]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[10].empty())
        {
            if(getIntrospectCount())
            {
                ret[pMasqueradingVector[10]]=getValueOfIntrospectCount();
            }
            else
            {
                ret[pMasqueradingVector[10]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[11].empty())
        {
            if(getRevokedAt())
            {
                ret[pMasqueradingVector[11]]=(Json::Int64)getValueOfRevokedAt();
            }
            else
            {
                ret[pMasqueradingVector[11]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[12].empty())
        {
            if(getRevokedBy())
            {
                ret[pMasqueradingVector[12]]=getValueOfRevokedBy();
            }
            else
            {
                ret[pMasqueradingVector[12]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[13].empty())
        {
            if(getOrgId())
            {
                ret[pMasqueradingVector[13]]=getValueOfOrgId();
            }
            else
            {
                ret[pMasqueradingVector[13]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getToken())
    {
        ret["token"]=getValueOfToken();
    }
    else
    {
        ret["token"]=Json::Value();
    }
    if(getClientId())
    {
        ret["client_id"]=getValueOfClientId();
    }
    else
    {
        ret["client_id"]=Json::Value();
    }
    if(getUserId())
    {
        ret["user_id"]=getValueOfUserId();
    }
    else
    {
        ret["user_id"]=Json::Value();
    }
    if(getScope())
    {
        ret["scope"]=getValueOfScope();
    }
    else
    {
        ret["scope"]=Json::Value();
    }
    if(getExpiresAt())
    {
        ret["expires_at"]=(Json::Int64)getValueOfExpiresAt();
    }
    else
    {
        ret["expires_at"]=Json::Value();
    }
    if(getRevoked())
    {
        ret["revoked"]=getValueOfRevoked();
    }
    else
    {
        ret["revoked"]=Json::Value();
    }
    if(getIssuedAt())
    {
        ret["issued_at"]=(Json::Int64)getValueOfIssuedAt();
    }
    else
    {
        ret["issued_at"]=Json::Value();
    }
    if(getIssuer())
    {
        ret["issuer"]=getValueOfIssuer();
    }
    else
    {
        ret["issuer"]=Json::Value();
    }
    if(getAudience())
    {
        ret["audience"]=getValueOfAudience();
    }
    else
    {
        ret["audience"]=Json::Value();
    }
    if(getNotBefore())
    {
        ret["not_before"]=(Json::Int64)getValueOfNotBefore();
    }
    else
    {
        ret["not_before"]=Json::Value();
    }
    if(getIntrospectCount())
    {
        ret["introspect_count"]=getValueOfIntrospectCount();
    }
    else
    {
        ret["introspect_count"]=Json::Value();
    }
    if(getRevokedAt())
    {
        ret["revoked_at"]=(Json::Int64)getValueOfRevokedAt();
    }
    else
    {
        ret["revoked_at"]=Json::Value();
    }
    if(getRevokedBy())
    {
        ret["revoked_by"]=getValueOfRevokedBy();
    }
    else
    {
        ret["revoked_by"]=Json::Value();
    }
    if(getOrgId())
    {
        ret["org_id"]=getValueOfOrgId();
    }
    else
    {
        ret["org_id"]=Json::Value();
    }
    return ret;
}

bool Oauth2AccessTokens::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("token"))
    {
        if(!validJsonOfField(0, "token", pJson["token"], err, true))
            return false;
    }
    else
    {
        err="The token column cannot be null";
        return false;
    }
    if(pJson.isMember("client_id"))
    {
        if(!validJsonOfField(1, "client_id", pJson["client_id"], err, true))
            return false;
    }
    else
    {
        err="The client_id column cannot be null";
        return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(2, "user_id", pJson["user_id"], err, true))
            return false;
    }
    if(pJson.isMember("scope"))
    {
        if(!validJsonOfField(3, "scope", pJson["scope"], err, true))
            return false;
    }
    if(pJson.isMember("expires_at"))
    {
        if(!validJsonOfField(4, "expires_at", pJson["expires_at"], err, true))
            return false;
    }
    else
    {
        err="The expires_at column cannot be null";
        return false;
    }
    if(pJson.isMember("revoked"))
    {
        if(!validJsonOfField(5, "revoked", pJson["revoked"], err, true))
            return false;
    }
    if(pJson.isMember("issued_at"))
    {
        if(!validJsonOfField(6, "issued_at", pJson["issued_at"], err, true))
            return false;
    }
    if(pJson.isMember("issuer"))
    {
        if(!validJsonOfField(7, "issuer", pJson["issuer"], err, true))
            return false;
    }
    if(pJson.isMember("audience"))
    {
        if(!validJsonOfField(8, "audience", pJson["audience"], err, true))
            return false;
    }
    if(pJson.isMember("not_before"))
    {
        if(!validJsonOfField(9, "not_before", pJson["not_before"], err, true))
            return false;
    }
    if(pJson.isMember("introspect_count"))
    {
        if(!validJsonOfField(10, "introspect_count", pJson["introspect_count"], err, true))
            return false;
    }
    if(pJson.isMember("revoked_at"))
    {
        if(!validJsonOfField(11, "revoked_at", pJson["revoked_at"], err, true))
            return false;
    }
    if(pJson.isMember("revoked_by"))
    {
        if(!validJsonOfField(12, "revoked_by", pJson["revoked_by"], err, true))
            return false;
    }
    if(pJson.isMember("org_id"))
    {
        if(!validJsonOfField(13, "org_id", pJson["org_id"], err, true))
            return false;
    }
    return true;
}
bool Oauth2AccessTokens::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                            const std::vector<std::string> &pMasqueradingVector,
                                                            std::string &err)
{
    if(pMasqueradingVector.size() != 14)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[0] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[4] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[9].empty())
      {
          if(pJson.isMember(pMasqueradingVector[9]))
          {
              if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[10].empty())
      {
          if(pJson.isMember(pMasqueradingVector[10]))
          {
              if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[11].empty())
      {
          if(pJson.isMember(pMasqueradingVector[11]))
          {
              if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[12].empty())
      {
          if(pJson.isMember(pMasqueradingVector[12]))
          {
              if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[13].empty())
      {
          if(pJson.isMember(pMasqueradingVector[13]))
          {
              if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Oauth2AccessTokens::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("token"))
    {
        if(!validJsonOfField(0, "token", pJson["token"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("client_id"))
    {
        if(!validJsonOfField(1, "client_id", pJson["client_id"], err, false))
            return false;
    }
    if(pJson.isMember("user_id"))
    {
        if(!validJsonOfField(2, "user_id", pJson["user_id"], err, false))
            return false;
    }
    if(pJson.isMember("scope"))
    {
        if(!validJsonOfField(3, "scope", pJson["scope"], err, false))
            return false;
    }
    if(pJson.isMember("expires_at"))
    {
        if(!validJsonOfField(4, "expires_at", pJson["expires_at"], err, false))
            return false;
    }
    if(pJson.isMember("revoked"))
    {
        if(!validJsonOfField(5, "revoked", pJson["revoked"], err, false))
            return false;
    }
    if(pJson.isMember("issued_at"))
    {
        if(!validJsonOfField(6, "issued_at", pJson["issued_at"], err, false))
            return false;
    }
    if(pJson.isMember("issuer"))
    {
        if(!validJsonOfField(7, "issuer", pJson["issuer"], err, false))
            return false;
    }
    if(pJson.isMember("audience"))
    {
        if(!validJsonOfField(8, "audience", pJson["audience"], err, false))
            return false;
    }
    if(pJson.isMember("not_before"))
    {
        if(!validJsonOfField(9, "not_before", pJson["not_before"], err, false))
            return false;
    }
    if(pJson.isMember("introspect_count"))
    {
        if(!validJsonOfField(10, "introspect_count", pJson["introspect_count"], err, false))
            return false;
    }
    if(pJson.isMember("revoked_at"))
    {
        if(!validJsonOfField(11, "revoked_at", pJson["revoked_at"], err, false))
            return false;
    }
    if(pJson.isMember("revoked_by"))
    {
        if(!validJsonOfField(12, "revoked_by", pJson["revoked_by"], err, false))
            return false;
    }
    if(pJson.isMember("org_id"))
    {
        if(!validJsonOfField(13, "org_id", pJson["org_id"], err, false))
            return false;
    }
    return true;
}
bool Oauth2AccessTokens::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                          const std::vector<std::string> &pMasqueradingVector,
                                                          std::string &err)
{
    if(pMasqueradingVector.size() != 14)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
      if(!pMasqueradingVector[9].empty() && pJson.isMember(pMasqueradingVector[9]))
      {
          if(!validJsonOfField(9, pMasqueradingVector[9], pJson[pMasqueradingVector[9]], err, false))
              return false;
      }
      if(!pMasqueradingVector[10].empty() && pJson.isMember(pMasqueradingVector[10]))
      {
          if(!validJsonOfField(10, pMasqueradingVector[10], pJson[pMasqueradingVector[10]], err, false))
              return false;
      }
      if(!pMasqueradingVector[11].empty() && pJson.isMember(pMasqueradingVector[11]))
      {
          if(!validJsonOfField(11, pMasqueradingVector[11], pJson[pMasqueradingVector[11]], err, false))
              return false;
      }
      if(!pMasqueradingVector[12].empty() && pJson.isMember(pMasqueradingVector[12]))
      {
          if(!validJsonOfField(12, pMasqueradingVector[12], pJson[pMasqueradingVector[12]], err, false))
              return false;
      }
      if(!pMasqueradingVector[13].empty() && pJson.isMember(pMasqueradingVector[13]))
      {
          if(!validJsonOfField(13, pMasqueradingVector[13], pJson[pMasqueradingVector[13]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool Oauth2AccessTokens::validJsonOfField(size_t index,
                                          const std::string &fieldName,
                                          const Json::Value &pJson,
                                          std::string &err,
                                          bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 100)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 100)";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isBool())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 255)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 255)";
                return false;
            }
            break;
        case 9:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 10:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 11:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt64())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 12:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }
            break;
        case 13:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
Oauth2Clients Oauth2AccessTokens::getClient(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from oauth2_clients where client_id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *clientId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return Oauth2Clients(r[0]);
}

void Oauth2AccessTokens::getClient(const DbClientPtr &clientPtr,
                                   const std::function<void(Oauth2Clients)> &rcb,
                                   const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from oauth2_clients where client_id = $1";
    *clientPtr << sql
               << *clientId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Oauth2Clients(r[0]));
                    }
               }
               >> ecb;
}
Organizations Oauth2AccessTokens::getOrganizations(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from organizations where id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *orgId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return Organizations(r[0]);
}

void Oauth2AccessTokens::getOrganizations(const DbClientPtr &clientPtr,
                                          const std::function<void(Organizations)> &rcb,
                                          const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from organizations where id = $1";
    *clientPtr << sql
               << *orgId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Organizations(r[0]));
                    }
               }
               >> ecb;
}
