/**
 *
 *  OrganizationConsentRequests.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "OrganizationConsentRequests.h"
#include "Oauth2Clients.h"
#include "Organizations.h"
#include "Users.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::fulla_db;

const std::string OrganizationConsentRequests::Cols::_id = "\"id\"";
const std::string OrganizationConsentRequests::Cols::_organization_id = "\"organization_id\"";
const std::string OrganizationConsentRequests::Cols::_client_id = "\"client_id\"";
const std::string OrganizationConsentRequests::Cols::_requested_by = "\"requested_by\"";
const std::string OrganizationConsentRequests::Cols::_requested_at = "\"requested_at\"";
const std::string OrganizationConsentRequests::Cols::_status = "\"status\"";
const std::string OrganizationConsentRequests::Cols::_decided_by = "\"decided_by\"";
const std::string OrganizationConsentRequests::Cols::_decided_at = "\"decided_at\"";
const std::string OrganizationConsentRequests::Cols::_reject_reason = "\"reject_reason\"";
const std::string OrganizationConsentRequests::primaryKeyName = "id";
const bool OrganizationConsentRequests::hasPrimaryKey = true;
const std::string OrganizationConsentRequests::tableName = "\"organization_consent_requests\"";

const std::vector<typename OrganizationConsentRequests::MetaData> OrganizationConsentRequests::metaData_={
{"id","int32_t","integer",4,1,1,1},
{"organization_id","int32_t","integer",4,0,0,1},
{"client_id","std::string","character varying",50,0,0,1},
{"requested_by","int32_t","integer",4,0,0,1},
{"requested_at","::trantor::Date","timestamp with time zone",0,0,0,0},
{"status","std::string","character varying",16,0,0,1},
{"decided_by","int32_t","integer",4,0,0,0},
{"decided_at","::trantor::Date","timestamp with time zone",0,0,0,0},
{"reject_reason","std::string","text",0,0,0,0}
};
const std::string &OrganizationConsentRequests::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
OrganizationConsentRequests::OrganizationConsentRequests(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["organization_id"].isNull())
        {
            organizationId_=std::make_shared<int32_t>(r["organization_id"].as<int32_t>());
        }
        if(!r["client_id"].isNull())
        {
            clientId_=std::make_shared<std::string>(r["client_id"].as<std::string>());
        }
        if(!r["requested_by"].isNull())
        {
            requestedBy_=std::make_shared<int32_t>(r["requested_by"].as<int32_t>());
        }
        if(!r["requested_at"].isNull())
        {
            auto timeStr = r["requested_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                requestedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["status"].isNull())
        {
            status_=std::make_shared<std::string>(r["status"].as<std::string>());
        }
        if(!r["decided_by"].isNull())
        {
            decidedBy_=std::make_shared<int32_t>(r["decided_by"].as<int32_t>());
        }
        if(!r["decided_at"].isNull())
        {
            auto timeStr = r["decided_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                decidedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["reject_reason"].isNull())
        {
            rejectReason_=std::make_shared<std::string>(r["reject_reason"].as<std::string>());
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 9 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            organizationId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            clientId_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            requestedBy_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                requestedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            status_=std::make_shared<std::string>(r[index].as<std::string>());
        }
        index = offset + 6;
        if(!r[index].isNull())
        {
            decidedBy_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 7;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                decidedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 8;
        if(!r[index].isNull())
        {
            rejectReason_=std::make_shared<std::string>(r[index].as<std::string>());
        }
    }

}

OrganizationConsentRequests::OrganizationConsentRequests(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 9)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            organizationId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            clientId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            requestedBy_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                requestedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            status_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            decidedBy_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[7]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                decidedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            rejectReason_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
}

OrganizationConsentRequests::OrganizationConsentRequests(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("organization_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["organization_id"].isNull())
        {
            organizationId_=std::make_shared<int32_t>((int32_t)pJson["organization_id"].asInt64());
        }
    }
    if(pJson.isMember("client_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["client_id"].isNull())
        {
            clientId_=std::make_shared<std::string>(pJson["client_id"].asString());
        }
    }
    if(pJson.isMember("requested_by"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["requested_by"].isNull())
        {
            requestedBy_=std::make_shared<int32_t>((int32_t)pJson["requested_by"].asInt64());
        }
    }
    if(pJson.isMember("requested_at"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["requested_at"].isNull())
        {
            auto timeStr = pJson["requested_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                requestedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("status"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["status"].isNull())
        {
            status_=std::make_shared<std::string>(pJson["status"].asString());
        }
    }
    if(pJson.isMember("decided_by"))
    {
        dirtyFlag_[6]=true;
        if(!pJson["decided_by"].isNull())
        {
            decidedBy_=std::make_shared<int32_t>((int32_t)pJson["decided_by"].asInt64());
        }
    }
    if(pJson.isMember("decided_at"))
    {
        dirtyFlag_[7]=true;
        if(!pJson["decided_at"].isNull())
        {
            auto timeStr = pJson["decided_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                decidedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("reject_reason"))
    {
        dirtyFlag_[8]=true;
        if(!pJson["reject_reason"].isNull())
        {
            rejectReason_=std::make_shared<std::string>(pJson["reject_reason"].asString());
        }
    }
}

void OrganizationConsentRequests::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 9)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            organizationId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            clientId_=std::make_shared<std::string>(pJson[pMasqueradingVector[2]].asString());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            requestedBy_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                requestedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            status_=std::make_shared<std::string>(pJson[pMasqueradingVector[5]].asString());
        }
    }
    if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
    {
        dirtyFlag_[6] = true;
        if(!pJson[pMasqueradingVector[6]].isNull())
        {
            decidedBy_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[6]].asInt64());
        }
    }
    if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
    {
        dirtyFlag_[7] = true;
        if(!pJson[pMasqueradingVector[7]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[7]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                decidedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
    {
        dirtyFlag_[8] = true;
        if(!pJson[pMasqueradingVector[8]].isNull())
        {
            rejectReason_=std::make_shared<std::string>(pJson[pMasqueradingVector[8]].asString());
        }
    }
}

void OrganizationConsentRequests::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("organization_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["organization_id"].isNull())
        {
            organizationId_=std::make_shared<int32_t>((int32_t)pJson["organization_id"].asInt64());
        }
    }
    if(pJson.isMember("client_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["client_id"].isNull())
        {
            clientId_=std::make_shared<std::string>(pJson["client_id"].asString());
        }
    }
    if(pJson.isMember("requested_by"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["requested_by"].isNull())
        {
            requestedBy_=std::make_shared<int32_t>((int32_t)pJson["requested_by"].asInt64());
        }
    }
    if(pJson.isMember("requested_at"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["requested_at"].isNull())
        {
            auto timeStr = pJson["requested_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                requestedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("status"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["status"].isNull())
        {
            status_=std::make_shared<std::string>(pJson["status"].asString());
        }
    }
    if(pJson.isMember("decided_by"))
    {
        dirtyFlag_[6] = true;
        if(!pJson["decided_by"].isNull())
        {
            decidedBy_=std::make_shared<int32_t>((int32_t)pJson["decided_by"].asInt64());
        }
    }
    if(pJson.isMember("decided_at"))
    {
        dirtyFlag_[7] = true;
        if(!pJson["decided_at"].isNull())
        {
            auto timeStr = pJson["decided_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                decidedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("reject_reason"))
    {
        dirtyFlag_[8] = true;
        if(!pJson["reject_reason"].isNull())
        {
            rejectReason_=std::make_shared<std::string>(pJson["reject_reason"].asString());
        }
    }
}

const int32_t &OrganizationConsentRequests::getValueOfId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &OrganizationConsentRequests::getId() const noexcept
{
    return id_;
}
void OrganizationConsentRequests::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename OrganizationConsentRequests::PrimaryKeyType & OrganizationConsentRequests::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int32_t &OrganizationConsentRequests::getValueOfOrganizationId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(organizationId_)
        return *organizationId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &OrganizationConsentRequests::getOrganizationId() const noexcept
{
    return organizationId_;
}
void OrganizationConsentRequests::setOrganizationId(const int32_t &pOrganizationId) noexcept
{
    organizationId_ = std::make_shared<int32_t>(pOrganizationId);
    dirtyFlag_[1] = true;
}

const std::string &OrganizationConsentRequests::getValueOfClientId() const noexcept
{
    static const std::string defaultValue = std::string();
    if(clientId_)
        return *clientId_;
    return defaultValue;
}
const std::shared_ptr<std::string> &OrganizationConsentRequests::getClientId() const noexcept
{
    return clientId_;
}
void OrganizationConsentRequests::setClientId(const std::string &pClientId) noexcept
{
    clientId_ = std::make_shared<std::string>(pClientId);
    dirtyFlag_[2] = true;
}
void OrganizationConsentRequests::setClientId(std::string &&pClientId) noexcept
{
    clientId_ = std::make_shared<std::string>(std::move(pClientId));
    dirtyFlag_[2] = true;
}

const int32_t &OrganizationConsentRequests::getValueOfRequestedBy() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(requestedBy_)
        return *requestedBy_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &OrganizationConsentRequests::getRequestedBy() const noexcept
{
    return requestedBy_;
}
void OrganizationConsentRequests::setRequestedBy(const int32_t &pRequestedBy) noexcept
{
    requestedBy_ = std::make_shared<int32_t>(pRequestedBy);
    dirtyFlag_[3] = true;
}

const ::trantor::Date &OrganizationConsentRequests::getValueOfRequestedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(requestedAt_)
        return *requestedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &OrganizationConsentRequests::getRequestedAt() const noexcept
{
    return requestedAt_;
}
void OrganizationConsentRequests::setRequestedAt(const ::trantor::Date &pRequestedAt) noexcept
{
    requestedAt_ = std::make_shared<::trantor::Date>(pRequestedAt);
    dirtyFlag_[4] = true;
}
void OrganizationConsentRequests::setRequestedAtToNull() noexcept
{
    requestedAt_.reset();
    dirtyFlag_[4] = true;
}

const std::string &OrganizationConsentRequests::getValueOfStatus() const noexcept
{
    static const std::string defaultValue = std::string();
    if(status_)
        return *status_;
    return defaultValue;
}
const std::shared_ptr<std::string> &OrganizationConsentRequests::getStatus() const noexcept
{
    return status_;
}
void OrganizationConsentRequests::setStatus(const std::string &pStatus) noexcept
{
    status_ = std::make_shared<std::string>(pStatus);
    dirtyFlag_[5] = true;
}
void OrganizationConsentRequests::setStatus(std::string &&pStatus) noexcept
{
    status_ = std::make_shared<std::string>(std::move(pStatus));
    dirtyFlag_[5] = true;
}

const int32_t &OrganizationConsentRequests::getValueOfDecidedBy() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(decidedBy_)
        return *decidedBy_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &OrganizationConsentRequests::getDecidedBy() const noexcept
{
    return decidedBy_;
}
void OrganizationConsentRequests::setDecidedBy(const int32_t &pDecidedBy) noexcept
{
    decidedBy_ = std::make_shared<int32_t>(pDecidedBy);
    dirtyFlag_[6] = true;
}
void OrganizationConsentRequests::setDecidedByToNull() noexcept
{
    decidedBy_.reset();
    dirtyFlag_[6] = true;
}

const ::trantor::Date &OrganizationConsentRequests::getValueOfDecidedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(decidedAt_)
        return *decidedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &OrganizationConsentRequests::getDecidedAt() const noexcept
{
    return decidedAt_;
}
void OrganizationConsentRequests::setDecidedAt(const ::trantor::Date &pDecidedAt) noexcept
{
    decidedAt_ = std::make_shared<::trantor::Date>(pDecidedAt);
    dirtyFlag_[7] = true;
}
void OrganizationConsentRequests::setDecidedAtToNull() noexcept
{
    decidedAt_.reset();
    dirtyFlag_[7] = true;
}

const std::string &OrganizationConsentRequests::getValueOfRejectReason() const noexcept
{
    static const std::string defaultValue = std::string();
    if(rejectReason_)
        return *rejectReason_;
    return defaultValue;
}
const std::shared_ptr<std::string> &OrganizationConsentRequests::getRejectReason() const noexcept
{
    return rejectReason_;
}
void OrganizationConsentRequests::setRejectReason(const std::string &pRejectReason) noexcept
{
    rejectReason_ = std::make_shared<std::string>(pRejectReason);
    dirtyFlag_[8] = true;
}
void OrganizationConsentRequests::setRejectReason(std::string &&pRejectReason) noexcept
{
    rejectReason_ = std::make_shared<std::string>(std::move(pRejectReason));
    dirtyFlag_[8] = true;
}
void OrganizationConsentRequests::setRejectReasonToNull() noexcept
{
    rejectReason_.reset();
    dirtyFlag_[8] = true;
}

void OrganizationConsentRequests::updateId(const uint64_t id)
{
}

const std::vector<std::string> &OrganizationConsentRequests::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "organization_id",
        "client_id",
        "requested_by",
        "requested_at",
        "status",
        "decided_by",
        "decided_at",
        "reject_reason"
    };
    return inCols;
}

void OrganizationConsentRequests::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getOrganizationId())
        {
            binder << getValueOfOrganizationId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getClientId())
        {
            binder << getValueOfClientId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getRequestedBy())
        {
            binder << getValueOfRequestedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getRequestedAt())
        {
            binder << getValueOfRequestedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getStatus())
        {
            binder << getValueOfStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getDecidedBy())
        {
            binder << getValueOfDecidedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getDecidedAt())
        {
            binder << getValueOfDecidedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getRejectReason())
        {
            binder << getValueOfRejectReason();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> OrganizationConsentRequests::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    if(dirtyFlag_[6])
    {
        ret.push_back(getColumnName(6));
    }
    if(dirtyFlag_[7])
    {
        ret.push_back(getColumnName(7));
    }
    if(dirtyFlag_[8])
    {
        ret.push_back(getColumnName(8));
    }
    return ret;
}

void OrganizationConsentRequests::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getOrganizationId())
        {
            binder << getValueOfOrganizationId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getClientId())
        {
            binder << getValueOfClientId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getRequestedBy())
        {
            binder << getValueOfRequestedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getRequestedAt())
        {
            binder << getValueOfRequestedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getStatus())
        {
            binder << getValueOfStatus();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[6])
    {
        if(getDecidedBy())
        {
            binder << getValueOfDecidedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[7])
    {
        if(getDecidedAt())
        {
            binder << getValueOfDecidedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[8])
    {
        if(getRejectReason())
        {
            binder << getValueOfRejectReason();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value OrganizationConsentRequests::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getOrganizationId())
    {
        ret["organization_id"]=getValueOfOrganizationId();
    }
    else
    {
        ret["organization_id"]=Json::Value();
    }
    if(getClientId())
    {
        ret["client_id"]=getValueOfClientId();
    }
    else
    {
        ret["client_id"]=Json::Value();
    }
    if(getRequestedBy())
    {
        ret["requested_by"]=getValueOfRequestedBy();
    }
    else
    {
        ret["requested_by"]=Json::Value();
    }
    if(getRequestedAt())
    {
        ret["requested_at"]=getRequestedAt()->toDbStringLocal();
    }
    else
    {
        ret["requested_at"]=Json::Value();
    }
    if(getStatus())
    {
        ret["status"]=getValueOfStatus();
    }
    else
    {
        ret["status"]=Json::Value();
    }
    if(getDecidedBy())
    {
        ret["decided_by"]=getValueOfDecidedBy();
    }
    else
    {
        ret["decided_by"]=Json::Value();
    }
    if(getDecidedAt())
    {
        ret["decided_at"]=getDecidedAt()->toDbStringLocal();
    }
    else
    {
        ret["decided_at"]=Json::Value();
    }
    if(getRejectReason())
    {
        ret["reject_reason"]=getValueOfRejectReason();
    }
    else
    {
        ret["reject_reason"]=Json::Value();
    }
    return ret;
}

std::string OrganizationConsentRequests::toString() const
{
    return toJson().toStyledString();
}

Json::Value OrganizationConsentRequests::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 9)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getOrganizationId())
            {
                ret[pMasqueradingVector[1]]=getValueOfOrganizationId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getClientId())
            {
                ret[pMasqueradingVector[2]]=getValueOfClientId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getRequestedBy())
            {
                ret[pMasqueradingVector[3]]=getValueOfRequestedBy();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getRequestedAt())
            {
                ret[pMasqueradingVector[4]]=getRequestedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getStatus())
            {
                ret[pMasqueradingVector[5]]=getValueOfStatus();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[6].empty())
        {
            if(getDecidedBy())
            {
                ret[pMasqueradingVector[6]]=getValueOfDecidedBy();
            }
            else
            {
                ret[pMasqueradingVector[6]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[7].empty())
        {
            if(getDecidedAt())
            {
                ret[pMasqueradingVector[7]]=getDecidedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[7]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[8].empty())
        {
            if(getRejectReason())
            {
                ret[pMasqueradingVector[8]]=getValueOfRejectReason();
            }
            else
            {
                ret[pMasqueradingVector[8]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getOrganizationId())
    {
        ret["organization_id"]=getValueOfOrganizationId();
    }
    else
    {
        ret["organization_id"]=Json::Value();
    }
    if(getClientId())
    {
        ret["client_id"]=getValueOfClientId();
    }
    else
    {
        ret["client_id"]=Json::Value();
    }
    if(getRequestedBy())
    {
        ret["requested_by"]=getValueOfRequestedBy();
    }
    else
    {
        ret["requested_by"]=Json::Value();
    }
    if(getRequestedAt())
    {
        ret["requested_at"]=getRequestedAt()->toDbStringLocal();
    }
    else
    {
        ret["requested_at"]=Json::Value();
    }
    if(getStatus())
    {
        ret["status"]=getValueOfStatus();
    }
    else
    {
        ret["status"]=Json::Value();
    }
    if(getDecidedBy())
    {
        ret["decided_by"]=getValueOfDecidedBy();
    }
    else
    {
        ret["decided_by"]=Json::Value();
    }
    if(getDecidedAt())
    {
        ret["decided_at"]=getDecidedAt()->toDbStringLocal();
    }
    else
    {
        ret["decided_at"]=Json::Value();
    }
    if(getRejectReason())
    {
        ret["reject_reason"]=getValueOfRejectReason();
    }
    else
    {
        ret["reject_reason"]=Json::Value();
    }
    return ret;
}

bool OrganizationConsentRequests::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("organization_id"))
    {
        if(!validJsonOfField(1, "organization_id", pJson["organization_id"], err, true))
            return false;
    }
    else
    {
        err="The organization_id column cannot be null";
        return false;
    }
    if(pJson.isMember("client_id"))
    {
        if(!validJsonOfField(2, "client_id", pJson["client_id"], err, true))
            return false;
    }
    else
    {
        err="The client_id column cannot be null";
        return false;
    }
    if(pJson.isMember("requested_by"))
    {
        if(!validJsonOfField(3, "requested_by", pJson["requested_by"], err, true))
            return false;
    }
    else
    {
        err="The requested_by column cannot be null";
        return false;
    }
    if(pJson.isMember("requested_at"))
    {
        if(!validJsonOfField(4, "requested_at", pJson["requested_at"], err, true))
            return false;
    }
    if(pJson.isMember("status"))
    {
        if(!validJsonOfField(5, "status", pJson["status"], err, true))
            return false;
    }
    if(pJson.isMember("decided_by"))
    {
        if(!validJsonOfField(6, "decided_by", pJson["decided_by"], err, true))
            return false;
    }
    if(pJson.isMember("decided_at"))
    {
        if(!validJsonOfField(7, "decided_at", pJson["decided_at"], err, true))
            return false;
    }
    if(pJson.isMember("reject_reason"))
    {
        if(!validJsonOfField(8, "reject_reason", pJson["reject_reason"], err, true))
            return false;
    }
    return true;
}
bool OrganizationConsentRequests::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                                     const std::vector<std::string> &pMasqueradingVector,
                                                                     std::string &err)
{
    if(pMasqueradingVector.size() != 9)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[6].empty())
      {
          if(pJson.isMember(pMasqueradingVector[6]))
          {
              if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[7].empty())
      {
          if(pJson.isMember(pMasqueradingVector[7]))
          {
              if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[8].empty())
      {
          if(pJson.isMember(pMasqueradingVector[8]))
          {
              if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool OrganizationConsentRequests::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("organization_id"))
    {
        if(!validJsonOfField(1, "organization_id", pJson["organization_id"], err, false))
            return false;
    }
    if(pJson.isMember("client_id"))
    {
        if(!validJsonOfField(2, "client_id", pJson["client_id"], err, false))
            return false;
    }
    if(pJson.isMember("requested_by"))
    {
        if(!validJsonOfField(3, "requested_by", pJson["requested_by"], err, false))
            return false;
    }
    if(pJson.isMember("requested_at"))
    {
        if(!validJsonOfField(4, "requested_at", pJson["requested_at"], err, false))
            return false;
    }
    if(pJson.isMember("status"))
    {
        if(!validJsonOfField(5, "status", pJson["status"], err, false))
            return false;
    }
    if(pJson.isMember("decided_by"))
    {
        if(!validJsonOfField(6, "decided_by", pJson["decided_by"], err, false))
            return false;
    }
    if(pJson.isMember("decided_at"))
    {
        if(!validJsonOfField(7, "decided_at", pJson["decided_at"], err, false))
            return false;
    }
    if(pJson.isMember("reject_reason"))
    {
        if(!validJsonOfField(8, "reject_reason", pJson["reject_reason"], err, false))
            return false;
    }
    return true;
}
bool OrganizationConsentRequests::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                                   const std::vector<std::string> &pMasqueradingVector,
                                                                   std::string &err)
{
    if(pMasqueradingVector.size() != 9)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
      if(!pMasqueradingVector[6].empty() && pJson.isMember(pMasqueradingVector[6]))
      {
          if(!validJsonOfField(6, pMasqueradingVector[6], pJson[pMasqueradingVector[6]], err, false))
              return false;
      }
      if(!pMasqueradingVector[7].empty() && pJson.isMember(pMasqueradingVector[7]))
      {
          if(!validJsonOfField(7, pMasqueradingVector[7], pJson[pMasqueradingVector[7]], err, false))
              return false;
      }
      if(!pMasqueradingVector[8].empty() && pJson.isMember(pMasqueradingVector[8]))
      {
          if(!validJsonOfField(8, pMasqueradingVector[8], pJson[pMasqueradingVector[8]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool OrganizationConsentRequests::validJsonOfField(size_t index,
                                                   const std::string &fieldName,
                                                   const Json::Value &pJson,
                                                   std::string &err,
                                                   bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 50)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 50)";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            if(pJson.isString() && std::wstring_convert<std::codecvt_utf8_utf16<wchar_t>, wchar_t>{}
                .from_bytes(pJson.asCString()).size() > 16)
            {
                err="String length exceeds limit for the " +
                    fieldName +
                    " field (the maximum value is 16)";
                return false;
            }
            break;
        case 6:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 7:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 8:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
Organizations OrganizationConsentRequests::getOrganizations(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from organizations where id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *organizationId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return Organizations(r[0]);
}

void OrganizationConsentRequests::getOrganizations(const DbClientPtr &clientPtr,
                                                   const std::function<void(Organizations)> &rcb,
                                                   const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from organizations where id = $1";
    *clientPtr << sql
               << *organizationId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Organizations(r[0]));
                    }
               }
               >> ecb;
}
Oauth2Clients OrganizationConsentRequests::getOauth2Clients(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from oauth2_clients where client_id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *clientId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return Oauth2Clients(r[0]);
}

void OrganizationConsentRequests::getOauth2Clients(const DbClientPtr &clientPtr,
                                                   const std::function<void(Oauth2Clients)> &rcb,
                                                   const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from oauth2_clients where client_id = $1";
    *clientPtr << sql
               << *clientId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Oauth2Clients(r[0]));
                    }
               }
               >> ecb;
}
Users OrganizationConsentRequests::getUsers(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from users where id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *requestedBy_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return Users(r[0]);
}

void OrganizationConsentRequests::getUsers(const DbClientPtr &clientPtr,
                                           const std::function<void(Users)> &rcb,
                                           const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from users where id = $1";
    *clientPtr << sql
               << *requestedBy_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Users(r[0]));
                    }
               }
               >> ecb;
}
