/**
 *
 *  OrganizationSuccessionNominations.cc
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#include "OrganizationSuccessionNominations.h"
#include "Organizations.h"
#include "Users.h"
#include <drogon/utils/Utilities.h>
#include <string>

using namespace drogon;
using namespace drogon::orm;
using namespace drogon_model::fulla_db;

const std::string OrganizationSuccessionNominations::Cols::_id = "\"id\"";
const std::string OrganizationSuccessionNominations::Cols::_organization_id = "\"organization_id\"";
const std::string OrganizationSuccessionNominations::Cols::_nominee_user_id = "\"nominee_user_id\"";
const std::string OrganizationSuccessionNominations::Cols::_nominated_by = "\"nominated_by\"";
const std::string OrganizationSuccessionNominations::Cols::_created_at = "\"created_at\"";
const std::string OrganizationSuccessionNominations::Cols::_accepted_at = "\"accepted_at\"";
const std::string OrganizationSuccessionNominations::primaryKeyName = "id";
const bool OrganizationSuccessionNominations::hasPrimaryKey = true;
const std::string OrganizationSuccessionNominations::tableName = "\"organization_succession_nominations\"";

const std::vector<typename OrganizationSuccessionNominations::MetaData> OrganizationSuccessionNominations::metaData_={
{"id","int32_t","integer",4,1,1,1},
{"organization_id","int32_t","integer",4,0,0,1},
{"nominee_user_id","int32_t","integer",4,0,0,1},
{"nominated_by","int32_t","integer",4,0,0,1},
{"created_at","::trantor::Date","timestamp with time zone",0,0,0,0},
{"accepted_at","::trantor::Date","timestamp with time zone",0,0,0,0}
};
const std::string &OrganizationSuccessionNominations::getColumnName(size_t index) noexcept(false)
{
    assert(index < metaData_.size());
    return metaData_[index].colName_;
}
OrganizationSuccessionNominations::OrganizationSuccessionNominations(const Row &r, const ssize_t indexOffset) noexcept
{
    if(indexOffset < 0)
    {
        if(!r["id"].isNull())
        {
            id_=std::make_shared<int32_t>(r["id"].as<int32_t>());
        }
        if(!r["organization_id"].isNull())
        {
            organizationId_=std::make_shared<int32_t>(r["organization_id"].as<int32_t>());
        }
        if(!r["nominee_user_id"].isNull())
        {
            nomineeUserId_=std::make_shared<int32_t>(r["nominee_user_id"].as<int32_t>());
        }
        if(!r["nominated_by"].isNull())
        {
            nominatedBy_=std::make_shared<int32_t>(r["nominated_by"].as<int32_t>());
        }
        if(!r["created_at"].isNull())
        {
            auto timeStr = r["created_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        if(!r["accepted_at"].isNull())
        {
            auto timeStr = r["accepted_at"].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                acceptedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    else
    {
        size_t offset = (size_t)indexOffset;
        if(offset + 6 > r.size())
        {
            LOG_FATAL << "Invalid SQL result for this model";
            return;
        }
        size_t index;
        index = offset + 0;
        if(!r[index].isNull())
        {
            id_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 1;
        if(!r[index].isNull())
        {
            organizationId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 2;
        if(!r[index].isNull())
        {
            nomineeUserId_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 3;
        if(!r[index].isNull())
        {
            nominatedBy_=std::make_shared<int32_t>(r[index].as<int32_t>());
        }
        index = offset + 4;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
        index = offset + 5;
        if(!r[index].isNull())
        {
            auto timeStr = r[index].as<std::string>();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                acceptedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }

}

OrganizationSuccessionNominations::OrganizationSuccessionNominations(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        dirtyFlag_[0] = true;
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            organizationId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            nomineeUserId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            nominatedBy_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                acceptedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

OrganizationSuccessionNominations::OrganizationSuccessionNominations(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        dirtyFlag_[0]=true;
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("organization_id"))
    {
        dirtyFlag_[1]=true;
        if(!pJson["organization_id"].isNull())
        {
            organizationId_=std::make_shared<int32_t>((int32_t)pJson["organization_id"].asInt64());
        }
    }
    if(pJson.isMember("nominee_user_id"))
    {
        dirtyFlag_[2]=true;
        if(!pJson["nominee_user_id"].isNull())
        {
            nomineeUserId_=std::make_shared<int32_t>((int32_t)pJson["nominee_user_id"].asInt64());
        }
    }
    if(pJson.isMember("nominated_by"))
    {
        dirtyFlag_[3]=true;
        if(!pJson["nominated_by"].isNull())
        {
            nominatedBy_=std::make_shared<int32_t>((int32_t)pJson["nominated_by"].asInt64());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[4]=true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("accepted_at"))
    {
        dirtyFlag_[5]=true;
        if(!pJson["accepted_at"].isNull())
        {
            auto timeStr = pJson["accepted_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                acceptedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void OrganizationSuccessionNominations::updateByMasqueradedJson(const Json::Value &pJson,
                                            const std::vector<std::string> &pMasqueradingVector) noexcept(false)
{
    if(pMasqueradingVector.size() != 6)
    {
        LOG_ERROR << "Bad masquerading vector";
        return;
    }
    if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
    {
        if(!pJson[pMasqueradingVector[0]].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[0]].asInt64());
        }
    }
    if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
    {
        dirtyFlag_[1] = true;
        if(!pJson[pMasqueradingVector[1]].isNull())
        {
            organizationId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[1]].asInt64());
        }
    }
    if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
    {
        dirtyFlag_[2] = true;
        if(!pJson[pMasqueradingVector[2]].isNull())
        {
            nomineeUserId_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[2]].asInt64());
        }
    }
    if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
    {
        dirtyFlag_[3] = true;
        if(!pJson[pMasqueradingVector[3]].isNull())
        {
            nominatedBy_=std::make_shared<int32_t>((int32_t)pJson[pMasqueradingVector[3]].asInt64());
        }
    }
    if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
    {
        dirtyFlag_[4] = true;
        if(!pJson[pMasqueradingVector[4]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[4]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
    {
        dirtyFlag_[5] = true;
        if(!pJson[pMasqueradingVector[5]].isNull())
        {
            auto timeStr = pJson[pMasqueradingVector[5]].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                acceptedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

void OrganizationSuccessionNominations::updateByJson(const Json::Value &pJson) noexcept(false)
{
    if(pJson.isMember("id"))
    {
        if(!pJson["id"].isNull())
        {
            id_=std::make_shared<int32_t>((int32_t)pJson["id"].asInt64());
        }
    }
    if(pJson.isMember("organization_id"))
    {
        dirtyFlag_[1] = true;
        if(!pJson["organization_id"].isNull())
        {
            organizationId_=std::make_shared<int32_t>((int32_t)pJson["organization_id"].asInt64());
        }
    }
    if(pJson.isMember("nominee_user_id"))
    {
        dirtyFlag_[2] = true;
        if(!pJson["nominee_user_id"].isNull())
        {
            nomineeUserId_=std::make_shared<int32_t>((int32_t)pJson["nominee_user_id"].asInt64());
        }
    }
    if(pJson.isMember("nominated_by"))
    {
        dirtyFlag_[3] = true;
        if(!pJson["nominated_by"].isNull())
        {
            nominatedBy_=std::make_shared<int32_t>((int32_t)pJson["nominated_by"].asInt64());
        }
    }
    if(pJson.isMember("created_at"))
    {
        dirtyFlag_[4] = true;
        if(!pJson["created_at"].isNull())
        {
            auto timeStr = pJson["created_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                createdAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
    if(pJson.isMember("accepted_at"))
    {
        dirtyFlag_[5] = true;
        if(!pJson["accepted_at"].isNull())
        {
            auto timeStr = pJson["accepted_at"].asString();
            struct tm stm;
            memset(&stm,0,sizeof(stm));
            auto p = strptime(timeStr.c_str(),"%Y-%m-%d %H:%M:%S",&stm);
            time_t t = mktime(&stm);
            size_t decimalNum = 0;
            if(p)
            {
                if(*p=='.')
                {
                    std::string decimals(p+1,&timeStr[timeStr.length()]);
                    while(decimals.length()<6)
                    {
                        decimals += "0";
                    }
                    decimalNum = (size_t)atol(decimals.c_str());
                }
                acceptedAt_=std::make_shared<::trantor::Date>(t*1000000+decimalNum);
            }
        }
    }
}

const int32_t &OrganizationSuccessionNominations::getValueOfId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(id_)
        return *id_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &OrganizationSuccessionNominations::getId() const noexcept
{
    return id_;
}
void OrganizationSuccessionNominations::setId(const int32_t &pId) noexcept
{
    id_ = std::make_shared<int32_t>(pId);
    dirtyFlag_[0] = true;
}
const typename OrganizationSuccessionNominations::PrimaryKeyType & OrganizationSuccessionNominations::getPrimaryKey() const
{
    assert(id_);
    return *id_;
}

const int32_t &OrganizationSuccessionNominations::getValueOfOrganizationId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(organizationId_)
        return *organizationId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &OrganizationSuccessionNominations::getOrganizationId() const noexcept
{
    return organizationId_;
}
void OrganizationSuccessionNominations::setOrganizationId(const int32_t &pOrganizationId) noexcept
{
    organizationId_ = std::make_shared<int32_t>(pOrganizationId);
    dirtyFlag_[1] = true;
}

const int32_t &OrganizationSuccessionNominations::getValueOfNomineeUserId() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(nomineeUserId_)
        return *nomineeUserId_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &OrganizationSuccessionNominations::getNomineeUserId() const noexcept
{
    return nomineeUserId_;
}
void OrganizationSuccessionNominations::setNomineeUserId(const int32_t &pNomineeUserId) noexcept
{
    nomineeUserId_ = std::make_shared<int32_t>(pNomineeUserId);
    dirtyFlag_[2] = true;
}

const int32_t &OrganizationSuccessionNominations::getValueOfNominatedBy() const noexcept
{
    static const int32_t defaultValue = int32_t();
    if(nominatedBy_)
        return *nominatedBy_;
    return defaultValue;
}
const std::shared_ptr<int32_t> &OrganizationSuccessionNominations::getNominatedBy() const noexcept
{
    return nominatedBy_;
}
void OrganizationSuccessionNominations::setNominatedBy(const int32_t &pNominatedBy) noexcept
{
    nominatedBy_ = std::make_shared<int32_t>(pNominatedBy);
    dirtyFlag_[3] = true;
}

const ::trantor::Date &OrganizationSuccessionNominations::getValueOfCreatedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(createdAt_)
        return *createdAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &OrganizationSuccessionNominations::getCreatedAt() const noexcept
{
    return createdAt_;
}
void OrganizationSuccessionNominations::setCreatedAt(const ::trantor::Date &pCreatedAt) noexcept
{
    createdAt_ = std::make_shared<::trantor::Date>(pCreatedAt);
    dirtyFlag_[4] = true;
}
void OrganizationSuccessionNominations::setCreatedAtToNull() noexcept
{
    createdAt_.reset();
    dirtyFlag_[4] = true;
}

const ::trantor::Date &OrganizationSuccessionNominations::getValueOfAcceptedAt() const noexcept
{
    static const ::trantor::Date defaultValue = ::trantor::Date();
    if(acceptedAt_)
        return *acceptedAt_;
    return defaultValue;
}
const std::shared_ptr<::trantor::Date> &OrganizationSuccessionNominations::getAcceptedAt() const noexcept
{
    return acceptedAt_;
}
void OrganizationSuccessionNominations::setAcceptedAt(const ::trantor::Date &pAcceptedAt) noexcept
{
    acceptedAt_ = std::make_shared<::trantor::Date>(pAcceptedAt);
    dirtyFlag_[5] = true;
}
void OrganizationSuccessionNominations::setAcceptedAtToNull() noexcept
{
    acceptedAt_.reset();
    dirtyFlag_[5] = true;
}

void OrganizationSuccessionNominations::updateId(const uint64_t id)
{
}

const std::vector<std::string> &OrganizationSuccessionNominations::insertColumns() noexcept
{
    static const std::vector<std::string> inCols={
        "organization_id",
        "nominee_user_id",
        "nominated_by",
        "created_at",
        "accepted_at"
    };
    return inCols;
}

void OrganizationSuccessionNominations::outputArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getOrganizationId())
        {
            binder << getValueOfOrganizationId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getNomineeUserId())
        {
            binder << getValueOfNomineeUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getNominatedBy())
        {
            binder << getValueOfNominatedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getAcceptedAt())
        {
            binder << getValueOfAcceptedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}

const std::vector<std::string> OrganizationSuccessionNominations::updateColumns() const
{
    std::vector<std::string> ret;
    if(dirtyFlag_[1])
    {
        ret.push_back(getColumnName(1));
    }
    if(dirtyFlag_[2])
    {
        ret.push_back(getColumnName(2));
    }
    if(dirtyFlag_[3])
    {
        ret.push_back(getColumnName(3));
    }
    if(dirtyFlag_[4])
    {
        ret.push_back(getColumnName(4));
    }
    if(dirtyFlag_[5])
    {
        ret.push_back(getColumnName(5));
    }
    return ret;
}

void OrganizationSuccessionNominations::updateArgs(drogon::orm::internal::SqlBinder &binder) const
{
    if(dirtyFlag_[1])
    {
        if(getOrganizationId())
        {
            binder << getValueOfOrganizationId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[2])
    {
        if(getNomineeUserId())
        {
            binder << getValueOfNomineeUserId();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[3])
    {
        if(getNominatedBy())
        {
            binder << getValueOfNominatedBy();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[4])
    {
        if(getCreatedAt())
        {
            binder << getValueOfCreatedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
    if(dirtyFlag_[5])
    {
        if(getAcceptedAt())
        {
            binder << getValueOfAcceptedAt();
        }
        else
        {
            binder << nullptr;
        }
    }
}
Json::Value OrganizationSuccessionNominations::toJson() const
{
    Json::Value ret;
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getOrganizationId())
    {
        ret["organization_id"]=getValueOfOrganizationId();
    }
    else
    {
        ret["organization_id"]=Json::Value();
    }
    if(getNomineeUserId())
    {
        ret["nominee_user_id"]=getValueOfNomineeUserId();
    }
    else
    {
        ret["nominee_user_id"]=Json::Value();
    }
    if(getNominatedBy())
    {
        ret["nominated_by"]=getValueOfNominatedBy();
    }
    else
    {
        ret["nominated_by"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getAcceptedAt())
    {
        ret["accepted_at"]=getAcceptedAt()->toDbStringLocal();
    }
    else
    {
        ret["accepted_at"]=Json::Value();
    }
    return ret;
}

std::string OrganizationSuccessionNominations::toString() const
{
    return toJson().toStyledString();
}

Json::Value OrganizationSuccessionNominations::toMasqueradedJson(
    const std::vector<std::string> &pMasqueradingVector) const
{
    Json::Value ret;
    if(pMasqueradingVector.size() == 6)
    {
        if(!pMasqueradingVector[0].empty())
        {
            if(getId())
            {
                ret[pMasqueradingVector[0]]=getValueOfId();
            }
            else
            {
                ret[pMasqueradingVector[0]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[1].empty())
        {
            if(getOrganizationId())
            {
                ret[pMasqueradingVector[1]]=getValueOfOrganizationId();
            }
            else
            {
                ret[pMasqueradingVector[1]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[2].empty())
        {
            if(getNomineeUserId())
            {
                ret[pMasqueradingVector[2]]=getValueOfNomineeUserId();
            }
            else
            {
                ret[pMasqueradingVector[2]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[3].empty())
        {
            if(getNominatedBy())
            {
                ret[pMasqueradingVector[3]]=getValueOfNominatedBy();
            }
            else
            {
                ret[pMasqueradingVector[3]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[4].empty())
        {
            if(getCreatedAt())
            {
                ret[pMasqueradingVector[4]]=getCreatedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[4]]=Json::Value();
            }
        }
        if(!pMasqueradingVector[5].empty())
        {
            if(getAcceptedAt())
            {
                ret[pMasqueradingVector[5]]=getAcceptedAt()->toDbStringLocal();
            }
            else
            {
                ret[pMasqueradingVector[5]]=Json::Value();
            }
        }
        return ret;
    }
    LOG_ERROR << "Masquerade failed";
    if(getId())
    {
        ret["id"]=getValueOfId();
    }
    else
    {
        ret["id"]=Json::Value();
    }
    if(getOrganizationId())
    {
        ret["organization_id"]=getValueOfOrganizationId();
    }
    else
    {
        ret["organization_id"]=Json::Value();
    }
    if(getNomineeUserId())
    {
        ret["nominee_user_id"]=getValueOfNomineeUserId();
    }
    else
    {
        ret["nominee_user_id"]=Json::Value();
    }
    if(getNominatedBy())
    {
        ret["nominated_by"]=getValueOfNominatedBy();
    }
    else
    {
        ret["nominated_by"]=Json::Value();
    }
    if(getCreatedAt())
    {
        ret["created_at"]=getCreatedAt()->toDbStringLocal();
    }
    else
    {
        ret["created_at"]=Json::Value();
    }
    if(getAcceptedAt())
    {
        ret["accepted_at"]=getAcceptedAt()->toDbStringLocal();
    }
    else
    {
        ret["accepted_at"]=Json::Value();
    }
    return ret;
}

bool OrganizationSuccessionNominations::validateJsonForCreation(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, true))
            return false;
    }
    if(pJson.isMember("organization_id"))
    {
        if(!validJsonOfField(1, "organization_id", pJson["organization_id"], err, true))
            return false;
    }
    else
    {
        err="The organization_id column cannot be null";
        return false;
    }
    if(pJson.isMember("nominee_user_id"))
    {
        if(!validJsonOfField(2, "nominee_user_id", pJson["nominee_user_id"], err, true))
            return false;
    }
    else
    {
        err="The nominee_user_id column cannot be null";
        return false;
    }
    if(pJson.isMember("nominated_by"))
    {
        if(!validJsonOfField(3, "nominated_by", pJson["nominated_by"], err, true))
            return false;
    }
    else
    {
        err="The nominated_by column cannot be null";
        return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(4, "created_at", pJson["created_at"], err, true))
            return false;
    }
    if(pJson.isMember("accepted_at"))
    {
        if(!validJsonOfField(5, "accepted_at", pJson["accepted_at"], err, true))
            return false;
    }
    return true;
}
bool OrganizationSuccessionNominations::validateMasqueradedJsonForCreation(const Json::Value &pJson,
                                                                           const std::vector<std::string> &pMasqueradingVector,
                                                                           std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty())
      {
          if(pJson.isMember(pMasqueradingVector[0]))
          {
              if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[1].empty())
      {
          if(pJson.isMember(pMasqueradingVector[1]))
          {
              if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[1] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[2].empty())
      {
          if(pJson.isMember(pMasqueradingVector[2]))
          {
              if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[2] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[3].empty())
      {
          if(pJson.isMember(pMasqueradingVector[3]))
          {
              if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, true))
                  return false;
          }
        else
        {
            err="The " + pMasqueradingVector[3] + " column cannot be null";
            return false;
        }
      }
      if(!pMasqueradingVector[4].empty())
      {
          if(pJson.isMember(pMasqueradingVector[4]))
          {
              if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, true))
                  return false;
          }
      }
      if(!pMasqueradingVector[5].empty())
      {
          if(pJson.isMember(pMasqueradingVector[5]))
          {
              if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, true))
                  return false;
          }
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool OrganizationSuccessionNominations::validateJsonForUpdate(const Json::Value &pJson, std::string &err)
{
    if(pJson.isMember("id"))
    {
        if(!validJsonOfField(0, "id", pJson["id"], err, false))
            return false;
    }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
    if(pJson.isMember("organization_id"))
    {
        if(!validJsonOfField(1, "organization_id", pJson["organization_id"], err, false))
            return false;
    }
    if(pJson.isMember("nominee_user_id"))
    {
        if(!validJsonOfField(2, "nominee_user_id", pJson["nominee_user_id"], err, false))
            return false;
    }
    if(pJson.isMember("nominated_by"))
    {
        if(!validJsonOfField(3, "nominated_by", pJson["nominated_by"], err, false))
            return false;
    }
    if(pJson.isMember("created_at"))
    {
        if(!validJsonOfField(4, "created_at", pJson["created_at"], err, false))
            return false;
    }
    if(pJson.isMember("accepted_at"))
    {
        if(!validJsonOfField(5, "accepted_at", pJson["accepted_at"], err, false))
            return false;
    }
    return true;
}
bool OrganizationSuccessionNominations::validateMasqueradedJsonForUpdate(const Json::Value &pJson,
                                                                         const std::vector<std::string> &pMasqueradingVector,
                                                                         std::string &err)
{
    if(pMasqueradingVector.size() != 6)
    {
        err = "Bad masquerading vector";
        return false;
    }
    try {
      if(!pMasqueradingVector[0].empty() && pJson.isMember(pMasqueradingVector[0]))
      {
          if(!validJsonOfField(0, pMasqueradingVector[0], pJson[pMasqueradingVector[0]], err, false))
              return false;
      }
    else
    {
        err = "The value of primary key must be set in the json object for update";
        return false;
    }
      if(!pMasqueradingVector[1].empty() && pJson.isMember(pMasqueradingVector[1]))
      {
          if(!validJsonOfField(1, pMasqueradingVector[1], pJson[pMasqueradingVector[1]], err, false))
              return false;
      }
      if(!pMasqueradingVector[2].empty() && pJson.isMember(pMasqueradingVector[2]))
      {
          if(!validJsonOfField(2, pMasqueradingVector[2], pJson[pMasqueradingVector[2]], err, false))
              return false;
      }
      if(!pMasqueradingVector[3].empty() && pJson.isMember(pMasqueradingVector[3]))
      {
          if(!validJsonOfField(3, pMasqueradingVector[3], pJson[pMasqueradingVector[3]], err, false))
              return false;
      }
      if(!pMasqueradingVector[4].empty() && pJson.isMember(pMasqueradingVector[4]))
      {
          if(!validJsonOfField(4, pMasqueradingVector[4], pJson[pMasqueradingVector[4]], err, false))
              return false;
      }
      if(!pMasqueradingVector[5].empty() && pJson.isMember(pMasqueradingVector[5]))
      {
          if(!validJsonOfField(5, pMasqueradingVector[5], pJson[pMasqueradingVector[5]], err, false))
              return false;
      }
    }
    catch(const Json::LogicError &e)
    {
      err = e.what();
      return false;
    }
    return true;
}
bool OrganizationSuccessionNominations::validJsonOfField(size_t index,
                                                         const std::string &fieldName,
                                                         const Json::Value &pJson,
                                                         std::string &err,
                                                         bool isForCreation)
{
    switch(index)
    {
        case 0:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(isForCreation)
            {
                err="The automatic primary key cannot be set";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 1:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 2:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 3:
            if(pJson.isNull())
            {
                err="The " + fieldName + " column cannot be null";
                return false;
            }
            if(!pJson.isInt())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 4:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        case 5:
            if(pJson.isNull())
            {
                return true;
            }
            if(!pJson.isString())
            {
                err="Type error in the "+fieldName+" field";
                return false;
            }
            break;
        default:
            err="Internal error in the server";
            return false;
    }
    return true;
}
Organizations OrganizationSuccessionNominations::getOrganizations(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from organizations where id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *organizationId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return Organizations(r[0]);
}

void OrganizationSuccessionNominations::getOrganizations(const DbClientPtr &clientPtr,
                                                         const std::function<void(Organizations)> &rcb,
                                                         const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from organizations where id = $1";
    *clientPtr << sql
               << *organizationId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Organizations(r[0]));
                    }
               }
               >> ecb;
}
Users OrganizationSuccessionNominations::getUsers(const DbClientPtr &clientPtr) const {
    static const std::string sql = "select * from users where id = $1";
    Result r(nullptr);
    {
        auto binder = *clientPtr << sql;
        binder << *nomineeUserId_ << Mode::Blocking >>
            [&r](const Result &result) { r = result; };
        binder.exec();
    }
    if (r.size() == 0)
    {
        throw UnexpectedRows("0 rows found");
    }
    else if (r.size() > 1)
    {
        throw UnexpectedRows("Found more than one row");
    }
    return Users(r[0]);
}

void OrganizationSuccessionNominations::getUsers(const DbClientPtr &clientPtr,
                                                 const std::function<void(Users)> &rcb,
                                                 const ExceptionCallback &ecb) const
{
    static const std::string sql = "select * from users where id = $1";
    *clientPtr << sql
               << *nomineeUserId_
               >> [rcb = std::move(rcb), ecb](const Result &r){
                    if (r.size() == 0)
                    {
                        ecb(UnexpectedRows("0 rows found"));
                    }
                    else if (r.size() > 1)
                    {
                        ecb(UnexpectedRows("Found more than one row"));
                    }
                    else
                    {
                        rcb(Users(r[0]));
                    }
               }
               >> ecb;
}
