/**
 *
 *  Oauth2Clients.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace fulla_db
{
class Oauth2AccessTokens;
class Oauth2ClientScopes;
class Oauth2Codes;
class Oauth2DeviceCodes;
class Oauth2RefreshTokens;
class Oauth2Scopes;
class Organizations;

class Oauth2Clients
{
  public:
    struct Cols
    {
        static const std::string _client_id;
        static const std::string _client_type;
        static const std::string _client_secret;
        static const std::string _salt;
        static const std::string _name;
        static const std::string _redirect_uris;
        static const std::string _allowed_grant_types;
        static const std::string _token_endpoint_auth_method;
        static const std::string _backchannel_logout_uri;
        static const std::string _backchannel_logout_session_required;
        static const std::string _org_id;
        static const std::string _deleted_at;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = std::string;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Oauth2Clients(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Oauth2Clients(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Oauth2Clients(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Oauth2Clients() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column client_id  */
    ///Get the value of the column client_id, returns the default value if the column is null
    const std::string &getValueOfClientId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getClientId() const noexcept;
    ///Set the value of the column client_id
    void setClientId(const std::string &pClientId) noexcept;
    void setClientId(std::string &&pClientId) noexcept;

    /**  For column client_type  */
    ///Get the value of the column client_type, returns the default value if the column is null
    const std::string &getValueOfClientType() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getClientType() const noexcept;
    ///Set the value of the column client_type
    void setClientType(const std::string &pClientType) noexcept;
    void setClientType(std::string &&pClientType) noexcept;

    /**  For column client_secret  */
    ///Get the value of the column client_secret, returns the default value if the column is null
    const std::string &getValueOfClientSecret() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getClientSecret() const noexcept;
    ///Set the value of the column client_secret
    void setClientSecret(const std::string &pClientSecret) noexcept;
    void setClientSecret(std::string &&pClientSecret) noexcept;

    /**  For column salt  */
    ///Get the value of the column salt, returns the default value if the column is null
    const std::string &getValueOfSalt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getSalt() const noexcept;
    ///Set the value of the column salt
    void setSalt(const std::string &pSalt) noexcept;
    void setSalt(std::string &&pSalt) noexcept;

    /**  For column name  */
    ///Get the value of the column name, returns the default value if the column is null
    const std::string &getValueOfName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getName() const noexcept;
    ///Set the value of the column name
    void setName(const std::string &pName) noexcept;
    void setName(std::string &&pName) noexcept;
    void setNameToNull() noexcept;

    /**  For column redirect_uris  */
    ///Get the value of the column redirect_uris, returns the default value if the column is null
    const std::string &getValueOfRedirectUris() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getRedirectUris() const noexcept;
    ///Set the value of the column redirect_uris
    void setRedirectUris(const std::string &pRedirectUris) noexcept;
    void setRedirectUris(std::string &&pRedirectUris) noexcept;
    void setRedirectUrisToNull() noexcept;

    /**  For column allowed_grant_types  */
    ///Get the value of the column allowed_grant_types, returns the default value if the column is null
    const std::string &getValueOfAllowedGrantTypes() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getAllowedGrantTypes() const noexcept;
    ///Set the value of the column allowed_grant_types
    void setAllowedGrantTypes(const std::string &pAllowedGrantTypes) noexcept;
    void setAllowedGrantTypes(std::string &&pAllowedGrantTypes) noexcept;
    void setAllowedGrantTypesToNull() noexcept;

    /**  For column token_endpoint_auth_method  */
    ///Get the value of the column token_endpoint_auth_method, returns the default value if the column is null
    const std::string &getValueOfTokenEndpointAuthMethod() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getTokenEndpointAuthMethod() const noexcept;
    ///Set the value of the column token_endpoint_auth_method
    void setTokenEndpointAuthMethod(const std::string &pTokenEndpointAuthMethod) noexcept;
    void setTokenEndpointAuthMethod(std::string &&pTokenEndpointAuthMethod) noexcept;
    void setTokenEndpointAuthMethodToNull() noexcept;

    /**  For column backchannel_logout_uri  */
    ///Get the value of the column backchannel_logout_uri, returns the default value if the column is null
    const std::string &getValueOfBackchannelLogoutUri() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getBackchannelLogoutUri() const noexcept;
    ///Set the value of the column backchannel_logout_uri
    void setBackchannelLogoutUri(const std::string &pBackchannelLogoutUri) noexcept;
    void setBackchannelLogoutUri(std::string &&pBackchannelLogoutUri) noexcept;
    void setBackchannelLogoutUriToNull() noexcept;

    /**  For column backchannel_logout_session_required  */
    ///Get the value of the column backchannel_logout_session_required, returns the default value if the column is null
    const bool &getValueOfBackchannelLogoutSessionRequired() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getBackchannelLogoutSessionRequired() const noexcept;
    ///Set the value of the column backchannel_logout_session_required
    void setBackchannelLogoutSessionRequired(const bool &pBackchannelLogoutSessionRequired) noexcept;
    void setBackchannelLogoutSessionRequiredToNull() noexcept;

    /**  For column org_id  */
    ///Get the value of the column org_id, returns the default value if the column is null
    const int32_t &getValueOfOrgId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getOrgId() const noexcept;
    ///Set the value of the column org_id
    void setOrgId(const int32_t &pOrgId) noexcept;
    void setOrgIdToNull() noexcept;

    /**  For column deleted_at  */
    ///Get the value of the column deleted_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfDeletedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getDeletedAt() const noexcept;
    ///Set the value of the column deleted_at
    void setDeletedAt(const ::trantor::Date &pDeletedAt) noexcept;
    void setDeletedAtToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 12;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
    std::vector<Oauth2AccessTokens> getAccessTokens(const drogon::orm::DbClientPtr &clientPtr) const;
    void getAccessTokens(const drogon::orm::DbClientPtr &clientPtr,
                         const std::function<void(std::vector<Oauth2AccessTokens>)> &rcb,
                         const drogon::orm::ExceptionCallback &ecb) const;
    std::vector<Oauth2RefreshTokens> getRefreshTokens(const drogon::orm::DbClientPtr &clientPtr) const;
    void getRefreshTokens(const drogon::orm::DbClientPtr &clientPtr,
                          const std::function<void(std::vector<Oauth2RefreshTokens>)> &rcb,
                          const drogon::orm::ExceptionCallback &ecb) const;
    std::vector<Oauth2Codes> getAuthCodes(const drogon::orm::DbClientPtr &clientPtr) const;
    void getAuthCodes(const drogon::orm::DbClientPtr &clientPtr,
                      const std::function<void(std::vector<Oauth2Codes>)> &rcb,
                      const drogon::orm::ExceptionCallback &ecb) const;
    std::vector<std::pair<Oauth2Scopes,Oauth2ClientScopes>> getScope(const drogon::orm::DbClientPtr &clientPtr) const;
    void getScope(const drogon::orm::DbClientPtr &clientPtr,
                  const std::function<void(std::vector<std::pair<Oauth2Scopes,Oauth2ClientScopes>>)> &rcb,
                  const drogon::orm::ExceptionCallback &ecb) const;
    std::vector<Oauth2DeviceCodes> getDeviceCodes(const drogon::orm::DbClientPtr &clientPtr) const;
    void getDeviceCodes(const drogon::orm::DbClientPtr &clientPtr,
                        const std::function<void(std::vector<Oauth2DeviceCodes>)> &rcb,
                        const drogon::orm::ExceptionCallback &ecb) const;
    Organizations getOrganizations(const drogon::orm::DbClientPtr &clientPtr) const;
    void getOrganizations(const drogon::orm::DbClientPtr &clientPtr,
                          const std::function<void(Organizations)> &rcb,
                          const drogon::orm::ExceptionCallback &ecb) const;
  private:
    friend drogon::orm::Mapper<Oauth2Clients>;
    friend drogon::orm::BaseBuilder<Oauth2Clients, true, true>;
    friend drogon::orm::BaseBuilder<Oauth2Clients, true, false>;
    friend drogon::orm::BaseBuilder<Oauth2Clients, false, true>;
    friend drogon::orm::BaseBuilder<Oauth2Clients, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Oauth2Clients>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<std::string> clientId_;
    std::shared_ptr<std::string> clientType_;
    std::shared_ptr<std::string> clientSecret_;
    std::shared_ptr<std::string> salt_;
    std::shared_ptr<std::string> name_;
    std::shared_ptr<std::string> redirectUris_;
    std::shared_ptr<std::string> allowedGrantTypes_;
    std::shared_ptr<std::string> tokenEndpointAuthMethod_;
    std::shared_ptr<std::string> backchannelLogoutUri_;
    std::shared_ptr<bool> backchannelLogoutSessionRequired_;
    std::shared_ptr<int32_t> orgId_;
    std::shared_ptr<::trantor::Date> deletedAt_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[12]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where client_id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where client_id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        if(dirtyFlag_[0])
        {
            sql += "client_id,";
            ++parametersCount;
        }
        sql += "client_type,";
        ++parametersCount;
        if(!dirtyFlag_[1])
        {
            needSelection=true;
        }
        if(dirtyFlag_[2])
        {
            sql += "client_secret,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "salt,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "name,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "redirect_uris,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "allowed_grant_types,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "token_endpoint_auth_method,";
            ++parametersCount;
        }
        if(dirtyFlag_[8])
        {
            sql += "backchannel_logout_uri,";
            ++parametersCount;
        }
        sql += "backchannel_logout_session_required,";
        ++parametersCount;
        if(!dirtyFlag_[9])
        {
            needSelection=true;
        }
        if(dirtyFlag_[10])
        {
            sql += "org_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[11])
        {
            sql += "deleted_at,";
            ++parametersCount;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        if(dirtyFlag_[0])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[8])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[9])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[10])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[11])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace fulla_db
} // namespace drogon_model
