/**
 *
 *  Oauth2Codes.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace fulla_db
{
class Oauth2Clients;
class Organizations;

class Oauth2Codes
{
  public:
    struct Cols
    {
        static const std::string _code;
        static const std::string _client_id;
        static const std::string _user_id;
        static const std::string _scope;
        static const std::string _redirect_uri;
        static const std::string _code_challenge;
        static const std::string _code_challenge_method;
        static const std::string _expires_at;
        static const std::string _used;
        static const std::string _auth_time;
        static const std::string _amr;
        static const std::string _nonce;
        static const std::string _org_id;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = std::string;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Oauth2Codes(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Oauth2Codes(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Oauth2Codes(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Oauth2Codes() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column code  */
    ///Get the value of the column code, returns the default value if the column is null
    const std::string &getValueOfCode() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getCode() const noexcept;
    ///Set the value of the column code
    void setCode(const std::string &pCode) noexcept;
    void setCode(std::string &&pCode) noexcept;

    /**  For column client_id  */
    ///Get the value of the column client_id, returns the default value if the column is null
    const std::string &getValueOfClientId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getClientId() const noexcept;
    ///Set the value of the column client_id
    void setClientId(const std::string &pClientId) noexcept;
    void setClientId(std::string &&pClientId) noexcept;

    /**  For column user_id  */
    ///Get the value of the column user_id, returns the default value if the column is null
    const std::string &getValueOfUserId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getUserId() const noexcept;
    ///Set the value of the column user_id
    void setUserId(const std::string &pUserId) noexcept;
    void setUserId(std::string &&pUserId) noexcept;
    void setUserIdToNull() noexcept;

    /**  For column scope  */
    ///Get the value of the column scope, returns the default value if the column is null
    const std::string &getValueOfScope() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getScope() const noexcept;
    ///Set the value of the column scope
    void setScope(const std::string &pScope) noexcept;
    void setScope(std::string &&pScope) noexcept;
    void setScopeToNull() noexcept;

    /**  For column redirect_uri  */
    ///Get the value of the column redirect_uri, returns the default value if the column is null
    const std::string &getValueOfRedirectUri() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getRedirectUri() const noexcept;
    ///Set the value of the column redirect_uri
    void setRedirectUri(const std::string &pRedirectUri) noexcept;
    void setRedirectUri(std::string &&pRedirectUri) noexcept;
    void setRedirectUriToNull() noexcept;

    /**  For column code_challenge  */
    ///Get the value of the column code_challenge, returns the default value if the column is null
    const std::string &getValueOfCodeChallenge() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getCodeChallenge() const noexcept;
    ///Set the value of the column code_challenge
    void setCodeChallenge(const std::string &pCodeChallenge) noexcept;
    void setCodeChallenge(std::string &&pCodeChallenge) noexcept;
    void setCodeChallengeToNull() noexcept;

    /**  For column code_challenge_method  */
    ///Get the value of the column code_challenge_method, returns the default value if the column is null
    const std::string &getValueOfCodeChallengeMethod() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getCodeChallengeMethod() const noexcept;
    ///Set the value of the column code_challenge_method
    void setCodeChallengeMethod(const std::string &pCodeChallengeMethod) noexcept;
    void setCodeChallengeMethod(std::string &&pCodeChallengeMethod) noexcept;
    void setCodeChallengeMethodToNull() noexcept;

    /**  For column expires_at  */
    ///Get the value of the column expires_at, returns the default value if the column is null
    const int64_t &getValueOfExpiresAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getExpiresAt() const noexcept;
    ///Set the value of the column expires_at
    void setExpiresAt(const int64_t &pExpiresAt) noexcept;

    /**  For column used  */
    ///Get the value of the column used, returns the default value if the column is null
    const bool &getValueOfUsed() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getUsed() const noexcept;
    ///Set the value of the column used
    void setUsed(const bool &pUsed) noexcept;
    void setUsedToNull() noexcept;

    /**  For column auth_time  */
    ///Get the value of the column auth_time, returns the default value if the column is null
    const int64_t &getValueOfAuthTime() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getAuthTime() const noexcept;
    ///Set the value of the column auth_time
    void setAuthTime(const int64_t &pAuthTime) noexcept;
    void setAuthTimeToNull() noexcept;

    /**  For column amr  */
    ///Get the value of the column amr, returns the default value if the column is null
    const std::string &getValueOfAmr() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getAmr() const noexcept;
    ///Set the value of the column amr
    void setAmr(const std::string &pAmr) noexcept;
    void setAmr(std::string &&pAmr) noexcept;
    void setAmrToNull() noexcept;

    /**  For column nonce  */
    ///Get the value of the column nonce, returns the default value if the column is null
    const std::string &getValueOfNonce() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getNonce() const noexcept;
    ///Set the value of the column nonce
    void setNonce(const std::string &pNonce) noexcept;
    void setNonce(std::string &&pNonce) noexcept;
    void setNonceToNull() noexcept;

    /**  For column org_id  */
    ///Get the value of the column org_id, returns the default value if the column is null
    const int32_t &getValueOfOrgId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getOrgId() const noexcept;
    ///Set the value of the column org_id
    void setOrgId(const int32_t &pOrgId) noexcept;
    void setOrgIdToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 13;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
    Oauth2Clients getClient(const drogon::orm::DbClientPtr &clientPtr) const;
    void getClient(const drogon::orm::DbClientPtr &clientPtr,
                   const std::function<void(Oauth2Clients)> &rcb,
                   const drogon::orm::ExceptionCallback &ecb) const;
    Organizations getOrganizations(const drogon::orm::DbClientPtr &clientPtr) const;
    void getOrganizations(const drogon::orm::DbClientPtr &clientPtr,
                          const std::function<void(Organizations)> &rcb,
                          const drogon::orm::ExceptionCallback &ecb) const;
  private:
    friend drogon::orm::Mapper<Oauth2Codes>;
    friend drogon::orm::BaseBuilder<Oauth2Codes, true, true>;
    friend drogon::orm::BaseBuilder<Oauth2Codes, true, false>;
    friend drogon::orm::BaseBuilder<Oauth2Codes, false, true>;
    friend drogon::orm::BaseBuilder<Oauth2Codes, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Oauth2Codes>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<std::string> code_;
    std::shared_ptr<std::string> clientId_;
    std::shared_ptr<std::string> userId_;
    std::shared_ptr<std::string> scope_;
    std::shared_ptr<std::string> redirectUri_;
    std::shared_ptr<std::string> codeChallenge_;
    std::shared_ptr<std::string> codeChallengeMethod_;
    std::shared_ptr<int64_t> expiresAt_;
    std::shared_ptr<bool> used_;
    std::shared_ptr<int64_t> authTime_;
    std::shared_ptr<std::string> amr_;
    std::shared_ptr<std::string> nonce_;
    std::shared_ptr<int32_t> orgId_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[13]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where code = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where code = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        if(dirtyFlag_[0])
        {
            sql += "code,";
            ++parametersCount;
        }
        if(dirtyFlag_[1])
        {
            sql += "client_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "user_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "scope,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "redirect_uri,";
            ++parametersCount;
        }
        if(dirtyFlag_[5])
        {
            sql += "code_challenge,";
            ++parametersCount;
        }
        if(dirtyFlag_[6])
        {
            sql += "code_challenge_method,";
            ++parametersCount;
        }
        if(dirtyFlag_[7])
        {
            sql += "expires_at,";
            ++parametersCount;
        }
        sql += "used,";
        ++parametersCount;
        if(!dirtyFlag_[8])
        {
            needSelection=true;
        }
        if(dirtyFlag_[9])
        {
            sql += "auth_time,";
            ++parametersCount;
        }
        if(dirtyFlag_[10])
        {
            sql += "amr,";
            ++parametersCount;
        }
        if(dirtyFlag_[11])
        {
            sql += "nonce,";
            ++parametersCount;
        }
        if(dirtyFlag_[12])
        {
            sql += "org_id,";
            ++parametersCount;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        if(dirtyFlag_[0])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[8])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[9])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[10])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[11])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[12])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace fulla_db
} // namespace drogon_model
