/**
 *
 *  Oauth2AccessTokens.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace fulla_db
{
class Oauth2Clients;
class Organizations;

class Oauth2AccessTokens
{
  public:
    struct Cols
    {
        static const std::string _token;
        static const std::string _client_id;
        static const std::string _user_id;
        static const std::string _scope;
        static const std::string _expires_at;
        static const std::string _revoked;
        static const std::string _issued_at;
        static const std::string _issuer;
        static const std::string _audience;
        static const std::string _not_before;
        static const std::string _introspect_count;
        static const std::string _revoked_at;
        static const std::string _revoked_by;
        static const std::string _org_id;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = std::string;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit Oauth2AccessTokens(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit Oauth2AccessTokens(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    Oauth2AccessTokens(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    Oauth2AccessTokens() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column token  */
    ///Get the value of the column token, returns the default value if the column is null
    const std::string &getValueOfToken() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getToken() const noexcept;
    ///Set the value of the column token
    void setToken(const std::string &pToken) noexcept;
    void setToken(std::string &&pToken) noexcept;

    /**  For column client_id  */
    ///Get the value of the column client_id, returns the default value if the column is null
    const std::string &getValueOfClientId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getClientId() const noexcept;
    ///Set the value of the column client_id
    void setClientId(const std::string &pClientId) noexcept;
    void setClientId(std::string &&pClientId) noexcept;

    /**  For column user_id  */
    ///Get the value of the column user_id, returns the default value if the column is null
    const std::string &getValueOfUserId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getUserId() const noexcept;
    ///Set the value of the column user_id
    void setUserId(const std::string &pUserId) noexcept;
    void setUserId(std::string &&pUserId) noexcept;
    void setUserIdToNull() noexcept;

    /**  For column scope  */
    ///Get the value of the column scope, returns the default value if the column is null
    const std::string &getValueOfScope() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getScope() const noexcept;
    ///Set the value of the column scope
    void setScope(const std::string &pScope) noexcept;
    void setScope(std::string &&pScope) noexcept;
    void setScopeToNull() noexcept;

    /**  For column expires_at  */
    ///Get the value of the column expires_at, returns the default value if the column is null
    const int64_t &getValueOfExpiresAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getExpiresAt() const noexcept;
    ///Set the value of the column expires_at
    void setExpiresAt(const int64_t &pExpiresAt) noexcept;

    /**  For column revoked  */
    ///Get the value of the column revoked, returns the default value if the column is null
    const bool &getValueOfRevoked() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<bool> &getRevoked() const noexcept;
    ///Set the value of the column revoked
    void setRevoked(const bool &pRevoked) noexcept;
    void setRevokedToNull() noexcept;

    /**  For column issued_at  */
    ///Get the value of the column issued_at, returns the default value if the column is null
    const int64_t &getValueOfIssuedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getIssuedAt() const noexcept;
    ///Set the value of the column issued_at
    void setIssuedAt(const int64_t &pIssuedAt) noexcept;

    /**  For column issuer  */
    ///Get the value of the column issuer, returns the default value if the column is null
    const std::string &getValueOfIssuer() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getIssuer() const noexcept;
    ///Set the value of the column issuer
    void setIssuer(const std::string &pIssuer) noexcept;
    void setIssuer(std::string &&pIssuer) noexcept;

    /**  For column audience  */
    ///Get the value of the column audience, returns the default value if the column is null
    const std::string &getValueOfAudience() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getAudience() const noexcept;
    ///Set the value of the column audience
    void setAudience(const std::string &pAudience) noexcept;
    void setAudience(std::string &&pAudience) noexcept;
    void setAudienceToNull() noexcept;

    /**  For column not_before  */
    ///Get the value of the column not_before, returns the default value if the column is null
    const int64_t &getValueOfNotBefore() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getNotBefore() const noexcept;
    ///Set the value of the column not_before
    void setNotBefore(const int64_t &pNotBefore) noexcept;
    void setNotBeforeToNull() noexcept;

    /**  For column introspect_count  */
    ///Get the value of the column introspect_count, returns the default value if the column is null
    const int32_t &getValueOfIntrospectCount() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getIntrospectCount() const noexcept;
    ///Set the value of the column introspect_count
    void setIntrospectCount(const int32_t &pIntrospectCount) noexcept;
    void setIntrospectCountToNull() noexcept;

    /**  For column revoked_at  */
    ///Get the value of the column revoked_at, returns the default value if the column is null
    const int64_t &getValueOfRevokedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int64_t> &getRevokedAt() const noexcept;
    ///Set the value of the column revoked_at
    void setRevokedAt(const int64_t &pRevokedAt) noexcept;
    void setRevokedAtToNull() noexcept;

    /**  For column revoked_by  */
    ///Get the value of the column revoked_by, returns the default value if the column is null
    const std::string &getValueOfRevokedBy() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getRevokedBy() const noexcept;
    ///Set the value of the column revoked_by
    void setRevokedBy(const std::string &pRevokedBy) noexcept;
    void setRevokedBy(std::string &&pRevokedBy) noexcept;
    void setRevokedByToNull() noexcept;

    /**  For column org_id  */
    ///Get the value of the column org_id, returns the default value if the column is null
    const int32_t &getValueOfOrgId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getOrgId() const noexcept;
    ///Set the value of the column org_id
    void setOrgId(const int32_t &pOrgId) noexcept;
    void setOrgIdToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 14;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
    Oauth2Clients getClient(const drogon::orm::DbClientPtr &clientPtr) const;
    void getClient(const drogon::orm::DbClientPtr &clientPtr,
                   const std::function<void(Oauth2Clients)> &rcb,
                   const drogon::orm::ExceptionCallback &ecb) const;
    Organizations getOrganizations(const drogon::orm::DbClientPtr &clientPtr) const;
    void getOrganizations(const drogon::orm::DbClientPtr &clientPtr,
                          const std::function<void(Organizations)> &rcb,
                          const drogon::orm::ExceptionCallback &ecb) const;
  private:
    friend drogon::orm::Mapper<Oauth2AccessTokens>;
    friend drogon::orm::BaseBuilder<Oauth2AccessTokens, true, true>;
    friend drogon::orm::BaseBuilder<Oauth2AccessTokens, true, false>;
    friend drogon::orm::BaseBuilder<Oauth2AccessTokens, false, true>;
    friend drogon::orm::BaseBuilder<Oauth2AccessTokens, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<Oauth2AccessTokens>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<std::string> token_;
    std::shared_ptr<std::string> clientId_;
    std::shared_ptr<std::string> userId_;
    std::shared_ptr<std::string> scope_;
    std::shared_ptr<int64_t> expiresAt_;
    std::shared_ptr<bool> revoked_;
    std::shared_ptr<int64_t> issuedAt_;
    std::shared_ptr<std::string> issuer_;
    std::shared_ptr<std::string> audience_;
    std::shared_ptr<int64_t> notBefore_;
    std::shared_ptr<int32_t> introspectCount_;
    std::shared_ptr<int64_t> revokedAt_;
    std::shared_ptr<std::string> revokedBy_;
    std::shared_ptr<int32_t> orgId_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[14]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where token = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where token = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
        if(dirtyFlag_[0])
        {
            sql += "token,";
            ++parametersCount;
        }
        if(dirtyFlag_[1])
        {
            sql += "client_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "user_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "scope,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "expires_at,";
            ++parametersCount;
        }
        sql += "revoked,";
        ++parametersCount;
        if(!dirtyFlag_[5])
        {
            needSelection=true;
        }
        sql += "issued_at,";
        ++parametersCount;
        if(!dirtyFlag_[6])
        {
            needSelection=true;
        }
        sql += "issuer,";
        ++parametersCount;
        if(!dirtyFlag_[7])
        {
            needSelection=true;
        }
        if(dirtyFlag_[8])
        {
            sql += "audience,";
            ++parametersCount;
        }
        sql += "not_before,";
        ++parametersCount;
        if(!dirtyFlag_[9])
        {
            needSelection=true;
        }
        sql += "introspect_count,";
        ++parametersCount;
        if(!dirtyFlag_[10])
        {
            needSelection=true;
        }
        if(dirtyFlag_[11])
        {
            sql += "revoked_at,";
            ++parametersCount;
        }
        if(dirtyFlag_[12])
        {
            sql += "revoked_by,";
            ++parametersCount;
        }
        if(dirtyFlag_[13])
        {
            sql += "org_id,";
            ++parametersCount;
        }
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        if(dirtyFlag_[0])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[7])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[8])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[9])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[10])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[11])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[12])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[13])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace fulla_db
} // namespace drogon_model
