/**
 *
 *  OrganizationConsents.h
 *  DO NOT EDIT. This file is generated by drogon_ctl
 *
 */

#pragma once
#include <drogon/orm/Result.h>
#include <drogon/orm/Row.h>
#include <drogon/orm/Field.h>
#include <drogon/orm/SqlBinder.h>
#include <drogon/orm/Mapper.h>
#include <drogon/orm/BaseBuilder.h>
#ifdef __cpp_impl_coroutine
#include <drogon/orm/CoroMapper.h>
#endif
#include <trantor/utils/Date.h>
#include <trantor/utils/Logger.h>
#include <json/json.h>
#include <string>
#include <string_view>
#include <memory>
#include <vector>
#include <tuple>
#include <stdint.h>
#include <iostream>

namespace drogon
{
namespace orm
{
class DbClient;
using DbClientPtr = std::shared_ptr<DbClient>;
}
}
namespace drogon_model
{
namespace fulla_db
{
class Oauth2Clients;
class Oauth2Scopes;
class Organizations;
class Users;

class OrganizationConsents
{
  public:
    struct Cols
    {
        static const std::string _id;
        static const std::string _organization_id;
        static const std::string _client_id;
        static const std::string _scope_name;
        static const std::string _granted_by;
        static const std::string _granted_at;
        static const std::string _revoked_at;
    };

    static const int primaryKeyNumber;
    static const std::string tableName;
    static const bool hasPrimaryKey;
    static const std::string primaryKeyName;
    using PrimaryKeyType = int32_t;
    const PrimaryKeyType &getPrimaryKey() const;

    /**
     * @brief constructor
     * @param r One row of records in the SQL query result.
     * @param indexOffset Set the offset to -1 to access all columns by column names,
     * otherwise access all columns by offsets.
     * @note If the SQL is not a style of 'select * from table_name ...' (select all
     * columns by an asterisk), please set the offset to -1.
     */
    explicit OrganizationConsents(const drogon::orm::Row &r, const ssize_t indexOffset = 0) noexcept;

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     */
    explicit OrganizationConsents(const Json::Value &pJson) noexcept(false);

    /**
     * @brief constructor
     * @param pJson The json object to construct a new instance.
     * @param pMasqueradingVector The aliases of table columns.
     */
    OrganizationConsents(const Json::Value &pJson, const std::vector<std::string> &pMasqueradingVector) noexcept(false);

    OrganizationConsents() = default;

    void updateByJson(const Json::Value &pJson) noexcept(false);
    void updateByMasqueradedJson(const Json::Value &pJson,
                                 const std::vector<std::string> &pMasqueradingVector) noexcept(false);
    static bool validateJsonForCreation(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForCreation(const Json::Value &,
                                                const std::vector<std::string> &pMasqueradingVector,
                                                    std::string &err);
    static bool validateJsonForUpdate(const Json::Value &pJson, std::string &err);
    static bool validateMasqueradedJsonForUpdate(const Json::Value &,
                                          const std::vector<std::string> &pMasqueradingVector,
                                          std::string &err);
    static bool validJsonOfField(size_t index,
                          const std::string &fieldName,
                          const Json::Value &pJson,
                          std::string &err,
                          bool isForCreation);

    /**  For column id  */
    ///Get the value of the column id, returns the default value if the column is null
    const int32_t &getValueOfId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getId() const noexcept;
    ///Set the value of the column id
    void setId(const int32_t &pId) noexcept;

    /**  For column organization_id  */
    ///Get the value of the column organization_id, returns the default value if the column is null
    const int32_t &getValueOfOrganizationId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getOrganizationId() const noexcept;
    ///Set the value of the column organization_id
    void setOrganizationId(const int32_t &pOrganizationId) noexcept;

    /**  For column client_id  */
    ///Get the value of the column client_id, returns the default value if the column is null
    const std::string &getValueOfClientId() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getClientId() const noexcept;
    ///Set the value of the column client_id
    void setClientId(const std::string &pClientId) noexcept;
    void setClientId(std::string &&pClientId) noexcept;

    /**  For column scope_name  */
    ///Get the value of the column scope_name, returns the default value if the column is null
    const std::string &getValueOfScopeName() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<std::string> &getScopeName() const noexcept;
    ///Set the value of the column scope_name
    void setScopeName(const std::string &pScopeName) noexcept;
    void setScopeName(std::string &&pScopeName) noexcept;

    /**  For column granted_by  */
    ///Get the value of the column granted_by, returns the default value if the column is null
    const int32_t &getValueOfGrantedBy() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<int32_t> &getGrantedBy() const noexcept;
    ///Set the value of the column granted_by
    void setGrantedBy(const int32_t &pGrantedBy) noexcept;

    /**  For column granted_at  */
    ///Get the value of the column granted_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfGrantedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getGrantedAt() const noexcept;
    ///Set the value of the column granted_at
    void setGrantedAt(const ::trantor::Date &pGrantedAt) noexcept;
    void setGrantedAtToNull() noexcept;

    /**  For column revoked_at  */
    ///Get the value of the column revoked_at, returns the default value if the column is null
    const ::trantor::Date &getValueOfRevokedAt() const noexcept;
    ///Return a shared_ptr object pointing to the column const value, or an empty shared_ptr object if the column is null
    const std::shared_ptr<::trantor::Date> &getRevokedAt() const noexcept;
    ///Set the value of the column revoked_at
    void setRevokedAt(const ::trantor::Date &pRevokedAt) noexcept;
    void setRevokedAtToNull() noexcept;


    static size_t getColumnNumber() noexcept {  return 7;  }
    static const std::string &getColumnName(size_t index) noexcept(false);

    Json::Value toJson() const;
    std::string toString() const;
    Json::Value toMasqueradedJson(const std::vector<std::string> &pMasqueradingVector) const;
    /// Relationship interfaces
    Organizations getOrganizations(const drogon::orm::DbClientPtr &clientPtr) const;
    void getOrganizations(const drogon::orm::DbClientPtr &clientPtr,
                          const std::function<void(Organizations)> &rcb,
                          const drogon::orm::ExceptionCallback &ecb) const;
    Oauth2Clients getOauth2Clients(const drogon::orm::DbClientPtr &clientPtr) const;
    void getOauth2Clients(const drogon::orm::DbClientPtr &clientPtr,
                          const std::function<void(Oauth2Clients)> &rcb,
                          const drogon::orm::ExceptionCallback &ecb) const;
    Oauth2Scopes getOauth2Scopes(const drogon::orm::DbClientPtr &clientPtr) const;
    void getOauth2Scopes(const drogon::orm::DbClientPtr &clientPtr,
                         const std::function<void(Oauth2Scopes)> &rcb,
                         const drogon::orm::ExceptionCallback &ecb) const;
    Users getUsers(const drogon::orm::DbClientPtr &clientPtr) const;
    void getUsers(const drogon::orm::DbClientPtr &clientPtr,
                  const std::function<void(Users)> &rcb,
                  const drogon::orm::ExceptionCallback &ecb) const;
  private:
    friend drogon::orm::Mapper<OrganizationConsents>;
    friend drogon::orm::BaseBuilder<OrganizationConsents, true, true>;
    friend drogon::orm::BaseBuilder<OrganizationConsents, true, false>;
    friend drogon::orm::BaseBuilder<OrganizationConsents, false, true>;
    friend drogon::orm::BaseBuilder<OrganizationConsents, false, false>;
#ifdef __cpp_impl_coroutine
    friend drogon::orm::CoroMapper<OrganizationConsents>;
#endif
    static const std::vector<std::string> &insertColumns() noexcept;
    void outputArgs(drogon::orm::internal::SqlBinder &binder) const;
    const std::vector<std::string> updateColumns() const;
    void updateArgs(drogon::orm::internal::SqlBinder &binder) const;
    ///For mysql or sqlite3
    void updateId(const uint64_t id);
    std::shared_ptr<int32_t> id_;
    std::shared_ptr<int32_t> organizationId_;
    std::shared_ptr<std::string> clientId_;
    std::shared_ptr<std::string> scopeName_;
    std::shared_ptr<int32_t> grantedBy_;
    std::shared_ptr<::trantor::Date> grantedAt_;
    std::shared_ptr<::trantor::Date> revokedAt_;
    struct MetaData
    {
        const std::string colName_;
        const std::string colType_;
        const std::string colDatabaseType_;
        const ssize_t colLength_;
        const bool isAutoVal_;
        const bool isPrimaryKey_;
        const bool notNull_;
    };
    static const std::vector<MetaData> metaData_;
    bool dirtyFlag_[7]={ false };
  public:
    static const std::string &sqlForFindingByPrimaryKey()
    {
        static const std::string sql="select * from " + tableName + " where id = $1";
        return sql;
    }

    static const std::string &sqlForDeletingByPrimaryKey()
    {
        static const std::string sql="delete from " + tableName + " where id = $1";
        return sql;
    }
    std::string sqlForInserting(bool &needSelection) const
    {
        std::string sql="insert into " + tableName + " (";
        size_t parametersCount = 0;
        needSelection = false;
            sql += "id,";
            ++parametersCount;
        if(dirtyFlag_[1])
        {
            sql += "organization_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[2])
        {
            sql += "client_id,";
            ++parametersCount;
        }
        if(dirtyFlag_[3])
        {
            sql += "scope_name,";
            ++parametersCount;
        }
        if(dirtyFlag_[4])
        {
            sql += "granted_by,";
            ++parametersCount;
        }
        sql += "granted_at,";
        ++parametersCount;
        if(!dirtyFlag_[5])
        {
            needSelection=true;
        }
        if(dirtyFlag_[6])
        {
            sql += "revoked_at,";
            ++parametersCount;
        }
        needSelection=true;
        if(parametersCount > 0)
        {
            sql[sql.length()-1]=')';
            sql += " values (";
        }
        else
            sql += ") values (";

        int placeholder=1;
        char placeholderStr[64];
        size_t n=0;
        sql +="default,";
        if(dirtyFlag_[1])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[2])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[3])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[4])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(dirtyFlag_[5])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        else
        {
            sql +="default,";
        }
        if(dirtyFlag_[6])
        {
            n = snprintf(placeholderStr,sizeof(placeholderStr),"$%d,",placeholder++);
            sql.append(placeholderStr, n);
        }
        if(parametersCount > 0)
        {
            sql.resize(sql.length() - 1);
        }
        if(needSelection)
        {
            sql.append(") returning *");
        }
        else
        {
            sql.append(1, ')');
        }
        LOG_TRACE << sql;
        return sql;
    }
};
} // namespace fulla_db
} // namespace drogon_model
